### ISSUE TITLE
Neverthromicon (wiki)

### ISSUE THREAD

**Issue by supermacro** [supermacro/neverthrow#131]
I started a [wiki](https://github.com/supermacro/neverthrow/wiki) for `neverthrow` that aims to document best practices on how to do error handling in a functional style.

This wiki is **very early stage** and am looking for help / suggestions / feedback.

**Comment by supermacro** [comment]
cc @paduc :)

**Comment by paduc** [comment]
Great initiative @supermacro. I'm currently refactoring my current project to use `neverthrow` everywhere. I might have a couple use-cases to showcase and discuss !

**Comment by supermacro** [comment]
I'm also thinking it might make more sense to use [Gitbook](https://docs.gitbook.com/integrations/github) and have a `wiki` folder in the project. That way, people can open PRs against the wiki.

**Comment by paduc** [comment]
I think the content is more important than the medium. The wiki is a great way to start the ball rolling !
