### ISSUE TITLE
Feature Request: '*Collect' API's

### ISSUE THREAD

**Issue by supermacro** [supermacro/neverthrow#186]
As discussed in https://github.com/supermacro/neverthrow/issues/183, specifically [this comment](https://github.com/supermacro/neverthrow/issues/183#issuecomment-730554613), it would be helpful if `neverthrow` had a way of accumulating the results of several computations in a long `map` / `andThen` chain. 

I sometimes find myself having to create custom objects that contain accumulated types which leads to a lot of noise in my code:

```typescript
interface CommentResponse {
  comments: Comment.WithReplies[]
  leafIds: string[]
  siteVerified: boolean
  postId: string
}

const getSiteComments = (
  siteId: Id,
  postId: CanonicalId
): ResultAsync<CommentResponse, RouteError> =>
  getSingleSite(siteId)
    .andThen((site) =>
      findOrCreatePost(postId, cuid(site.id))
        .map((post) => ({ post, site })) // <--- create a custom object / type that allows me to "save" the result of several computations
    )
    .andThen(({ post, site }) => // <----- unwrap the object / type here
      getComments(site.id, post.id).map((comments) => ({
        comments,
        siteVerified: site.verified,
        postId: post.id,
        leafIds: commentTreeLeafState.getLeafCommentsForPost(cuid(post.id)),
      }))
    )
```

The above example only "saves" results once, but I imagine there might be more complex / longer chains that require saving even more results (as described in https://github.com/supermacro/neverthrow/issues/183) that would make this pattern really distracting.

### Desired Outcome

Create a `mapCollect` and `andThenCollect` methods that work just like `map` and `andThen` respectively but additionally saves the result of the previous computation in a tuple:

```typescript
type AndThenFunc = (t:  T) => ResultAsync<U, E> | Result<U, E>
ResultAsync<T, E>.andThenCollect<U>(f: AndThenFunc): ResultAsync<[U, T], E> { ... }

//  ...

ResultAsync<T, E>.map<U>(f: (val: T) => U): ResultAsync<[U, T], E> { ... }
```

As mentioned in the original issue:

... you'd end up with nested tuples (such as [A, [B, [ C, D ] ] ]) if you chained multiple calls to andThenCollect. But there might be a way to overload the function implementation to provide different type definitions so as to have a flat tuple instead of nested tuples irrespective of how many times andThenCollect is called.

**Comment by paduc** [comment]
Hi @supermacro,

I've had the same desire (albeit not very often) but have managed with using `map` to create the composite return value. I'm not sure the pain is not big enough to change.

`andThenCollect` seems to be syntactic sugar for `andThen((res1) => fn().map((res2) => [res1,res2]))`. Am I missing something ?

**Comment by supermacro** [comment]
Hey @paduc,

I do the same pattern as well, except always with objects since I can destructure the object in a subsequent `.map` or `.andThen` call. 

However, as described by @bluenote10 in the original issue, sometimes this pattern can lead to a lot of noise in the code and make reading a chain harder. Thus I do see some value to having these utility methods. Wouldn't hurt to have them IMO. 

I also imagine that reducing noise / boilerplate in the code might help in persuading a skeptical group of colleagues who aren't yet familiar with a package like `neverthrow`.

**Comment by tam-carre** [comment]
If this is reopened, I might give it a try.

The need to unnest interdependent monadic computations is pervasive in programming that uses them. It is the primary purpose of JS async/await, Rust question mark operator, and do notation in Haskell.

Manually mapping values to accumulate data is pretty noisy and obscures the computation chain's high level logic. This Collect API proposal seems a lot more convenient

**Comment by supermacro** [comment]
I'd be interested in seeing a proposed API of this :point_up:

**Comment by brndt** [comment]
> If this is reopened, I might give it a try.
> 
> The need to unnest interdependent monadic computations is pervasive in programming languages that use them. It is the primary purpose of JS async/await, Rust question mark operator, and do notation in Haskell.
> 
> Manually mapping values to accumulate data is pretty noisy and obscures the computation chain's high level logic. This Collect API proposal seems a lot more convenient

It would be great if the library had this API.
