### ISSUE TITLE
Add Synchronous API to wrap a synchronous function that throws

### ISSUE THREAD

**Issue by Liam-Tait** [supermacro/neverthrow#203]
Synchronous functions that throw are quite common.

I suggest a function is added to the Synchronous API to wrap these functions to return `ok` or `err`.

This could be achieved using a higher order function to wrap the synchronous function that throws

A built in example of this is `JSON.stringify`

The following error throws `TypeError: Converting circular structure to JSON`
```ts
const circularReference =  {};
circularReference.myself = circularReference;
JSON.stringify(circularReference);
```

I would suggest the utility function would wrap the function keeping the same arguments and modifying the return type to be
a Result

```ts
const JsonStringify = wrapSynchronousFn(JSON.stringify);
const jsonResult = JsonStringify(circularReference);
JsonStringify(circularReference).isOk(); // false
```

An initial pass could look something like the following. I don't think it would be possible to infer the thrown Errors, so this may need to be modified

```ts
function wrapSynchronousFn<ARGUMENTS extends readonly any[], ReturnValue, Fn extends (...args: ARGUMENTS) => ReturnValue, E>(
  fn: Fn
): (...args: ARGUMENTS) => Result<ReturnValue, E> {
  return (...args: ARGUMENTS) => {
    try {
      const result = fn(...args);
      return ok(result);
    } catch (e) {
      return err(e);
    }
  };
}
```

Please let me know if this direction would be accepted. I am happy to work on this with any suggested changes.

**Comment by paduc** [comment]
Hi @Liam-Tait, I could see myself enjoying such a helper !

I would however suggest a syntax closer to `ResultAsync.fromPromise`, maybe `Result.fromThrowable`.

I would use it like this:
```typescript
const res = Result.fromThrowable( () => fnThatMayThrow(), (e) => new MyCustomError(e.message) );
// res is Result<ReturnType<typeof fnThatMayThrow>, MyCustomError>
```

**Comment by Liam-Tait** [comment]
@paduc Thanks for taking the time to review this suggestion.


As `Result` is a type and not a class. this would have to be a function to work.

Adding an optional errorFn makes sense and keeps the API consistent

I suggest that having the function be higher order promotes better readability and re-usability.
In the wiki there is an example for Wrapping 3rd party code to localize exceptions
https://github.com/supermacro/neverthrow/wiki/Error-Handling-Best-Practices#synchronous-example
Which lends itself to the wrapping approach.

With above changes this would become either

**Wrapping**
```ts
import { fromThrowable } form 'nevethrow'

const safeJsonParse = fromThrowable(Json.parse, intoParseError)

const jsonResult1 = safeJsonParse(jsonString1);
const jsonResult2 = safeJsonParse(jsonString2);
```

**Closer to fromPromise**
```ts
import { fromThrowable } form 'nevethrow'

const jsonResult1 = fromThrowable(() => JSON.parse(jsonString1), intoParseError)
const jsonResult2 = fromThrowable(() => JSON.parse(jsonString2), intoParseError)
```

**Comment by paduc** [comment]
@Liam-Tait you are absolutely right about `Result` being a type. A utility function would work great.

I guess the wrapping method is nicer when reusing the wrapped function a lot (and would work like `utils.promisify`).

The syntax similar to `fromPromise` feels more natural when using with an anonymous function. It would be an equivalent of `try...catch` where the first argument would be the contents of the `try` scope and the second argument would be the contents of the `catch` scope. 

I personnally would use the latter more often but I guess both would work.

What do you think @supermacro ?

**Comment by supermacro** [comment]
Hey @Liam-Tait, thanks for the proposal! 

> As `Result` is a type and not a class. this would have to be a function to work.

You could create a namespace in order to have a `Result.fromThrowable` api:

```typescript
// inside result.ts
export namesapce Result {
  export const fromThrowable = ...
}
```

I like this approach because then you can call `Result.fromThrowable`, which in my opinion signals intent a bit better than by just calling it on its own. 

---

I personally like the "wrap" design because of its simplicity. It's narrowly focused on creating a new function from an unsafe function. 

The reason I do not like the design that is closer to "fromPromise" is because it tries to replace the `try / catch` statements, without much benefit in my opinion.
