### ISSUE TITLE
Add eslint `must-use` flag.

### ISSUE THREAD

**Issue by supermacro** [supermacro/neverthrow#212]
While reading through the docs of Rust's [`Result`](https://doc.rust-lang.org/std/result/#results-must-be-used) type, I learned that they annotate `Result` with a compiler attribute that enforces a user to "do something" with the result.

**It might be nice to introduce an eslint rule that does this for neverthrow.**

It would prevent situations like this:

```typescript
const doSomethingThatMayFail = async () => {
  await changeUserPassword() // Returns a `Result<null, DbError>`
}
```

Note that we haven't checked to see if `changeUserPassword` actually succeeded.

--- 

Edit:

### Learning Resources:

- https://dev.to/spukas/how-to-write-your-first-eslint-plugin-145
- https://dev.to/alexgomesdev/writing-custom-typescript-eslint-rules-how-i-learned-to-love-the-ast-15pn

**Comment by paduc** [comment]
I agree we always need to "do something" with the result but it can be anywhere in the call stack. I don't see the issue in your example. I can check if `changeUserPassword()` has succeeded at the place of the call to `doSomethingThatMayFail()`.

So I guess we would try to forbid calling a method that returns a `Result` without checking the result type _or forwarding it (can be andThen, match or return)_.

**Comment by supermacro** [comment]
> I don't see the issue in your example. I can check if changeUserPassword() has succeeded at the place of the call to doSomethingThatMayFail()

How? `doSomethingThatMayFail` does not return a `Result` / `ResultAsync`.

**Comment by paduc** [comment]
@supermacro I apologies, I misread your initial example and didn't notice that `doSomethingThatMayFail` returned nothing.

It would be interesting to have an eslint plugin for this situation indeed !

**Comment by supermacro** [comment]
**$150 USD bounty** for anyone that solves this

**Comment by supermacro** [comment]
Amazing, I'll have a read through `eslint-plugin-nevethrow` this week 👍 

> should i push the package to npm or you do it?

I personally plan on maintaining `neverthrow` (and now `eslint-plugin-nevethrow`) ... maybe what would make sense is if you make me a privileged collaborator to https://github.com/mdbetancourt/eslint-plugin-nevethrow (with permission to merge and / or push directly to your main branch if that's ok) + also make me a privileged collaborator on the npm lib (you can push if you'd like to).


> can i ask, can you put a link in you readme referencing my project? i did so with neverthrow
> https://github.com/kraftrio/kraftr/tree/develop/core/errors

Potentially. Once I go over the lint rule you created and am happy with it (and send you the bounty 😄) then I'll most likely end up updating the README with a link to the `eslint-plugin-nevethrow` repo and a reference to your GH profile (https://github.com/mdbetancourt).

**Comment by supermacro** [comment]
@mdbetancourt I have a PR up on your repo:

https://github.com/mdbetancourt/eslint-plugin-nevethrow/pull/2

This **work in progress* / draft PR still requires implementing the actual logic to allow the test to pass.

**Comment by supermacro** [comment]
Thanks for addressing those changes @mdbetancourt!

Last few things:

- [ ] publish `eslint-plugin-nevethrow` to npm
- [ ] I will try out the plugin in our Caribou codebase and test that things are good (hopefully no more tweaks and changes)
- [ ] send over a well-deserved bounty :)

**Comment by mdbetancourt** [comment]
>  publish eslint-plugin-nevethrow to npm
@supermacro is already published since yesterday, the reported issue was a misconfiguration in the package.json file

> I will try out the plugin in our Caribou codebase and test that things are good (hopefully no more tweaks and changes)
perfect i hope hear good news from you soon

> send over a well-deserved bounty :)
thank you :) I wrote you on twitter, when you finished we can talk about the payment there

**Comment by supermacro** [comment]
Can confirm that things are working fantastic with `eslint-plugin-neverthrow` ... amazing work @mdbetancourt.

As discussed privately, payment is on its way.

**Comment by WesleyYue** [comment]
I think the original case in the first post is actually still not solved with the eslint plugin as the eslint plugin currently [does not work with await](https://github.com/mdbetancourt/eslint-plugin-neverthrow/issues/10). I'm happy to put a $50 bounty for a fix (with an expiration date of 6 months on the bounty, just so I don't forget about it and not pay out if someone fixes this in like 3 years).

**Comment by Bistard** [comment]
> I think the original case in the first post is actually still not solved with the eslint plugin as the eslint plugin currently [does not work with await](https://github.com/mdbetancourt/eslint-plugin-neverthrow/issues/10). I'm happy to put a $50 bounty for a fix (with an expiration date of 6 months on the bounty, just so I don't forget about it and not pay out if someone fixes this in like 3 years).

I encountered the same problem, I'm currently modifying the source code of `eslint-plugin-neverthrow`. I think I can solve this very soon.

**Comment by Bistard** [comment]
I think I solved [does not work with await](https://github.com/mdbetancourt/eslint-plugin-neverthrow/issues/10).

I think the issue is extremely simple, I realize it can be solved with 1-3 lines.

Currently my version of eslint will consider the following as unhandled:
```ts
test('await keyword', async () => {
            const test_result = await returnAsyncResult(true);
            // test_result.unwrap(); // unhandled -> rea underline
        });
```
![image](https://github.com/supermacro/neverthrow/assets/38385498/3b6cdb6e-a169-4853-9650-3d2fff185c05)
