### ISSUE TITLE
Add convenience method to create a ResultAsync from Result

### ISSUE THREAD

**Issue by Sajjon** [supermacro/neverthrow#221]
In non-Result(neverthrow)-land, using vanilla `Promise` we can easily convert a non-async method to be `async` using `Promise.resolve('myString)` which returns `Promise<string>`.

What is the equivalence using `ResultAsync`? I.e. I want to super easily convert a `Result<T, E>` to `ResultAsync<T, E>`.

I've managed to do it using this code - but feels like there must be (or should be) an easier way:

```typescript
export const resultToAsync = <T, E>(
	result: Result<T, E>,
): ResultAsync<T, E> => {
	return result.asyncAndThen((value) => {
		return okAsync(value)
	})
}
```

**Comment by paduc** [comment]
Hello @Sajjon !

I would say that `okAsync` is the `neverthrow` equivalent of `Promise.resolve`.

Can you tell us a bit more about the use-case that brought this up ?

**Comment by Sajjon** [comment]
@paduc hmm ok wrong dimension of equivalence :D I did not mean a constructor taking a value, e.g. 'myString' and returning `ResultAsync<string, Error>` from it. 

I meant what I posted above....

An easy way to go from `Result<T, E>` to `ResultAsync<T, E>`, which is exactly what I managed to to above. But I was wondering if there is a shorter and sweeter version than what I do above?? :) 

The use-case is that I have something in the sync world that I would like to wrap as async. Because I have another implementation which is async, and I would like to expose the same uniform (async) API for these two different implementations.

**Comment by paduc** [comment]
I understood the solution you are aiming at but would like to know more about the context of the problem, to understand if there is a good enough reason to add a utility function (like you are suggesting) or if the problem can be addressed by a more idiomatic approach (ie using the current API as it is intended).

You're not telling me *why* you need a uniform API for the two implementations. Is it possible that the caller could use part of the API that accepts both `Result` and `ResultAsync` types, like for instance `ResultAsync.andThen` ?

**Comment by Sajjon** [comment]
Sorry I will give more info, and also please bear in mind that I'm not a JS/TS export, nor a fan of these languages, coming from the Swift world I'm quite spoiled with proper strong types and error handling, also native support for `Result` - so I might not use the most precise wording and/or have misunderstood things.

I'm working on a crypto project where the user can produce cryptographic signatures of some data, e.g. transfer to tokens she owns. "Owning" a token is an implicit thing, it means having the capability of signing a token transfer spending said tokens.  The signing schema used is Elliptic Curve Cryptography (ECC), where a `PrivateKey` is used to sign data (a transaction, e.g. a token transfer). 

However, sometimes the user does not have direct access to the privateKey, in the scenario where she is using what is called a hardware wallet (like a special secure USB stick, storing the privateKey, e.g. a _"Ledger Nano S"_ ), the privateKey never exposed to the user, rather this flow is async, a host machine sends a transaction to the hardware wallet, and the user then needs to physically accept the signing of this transaction with hardware buttons on the USB stick.

Therefore the singing is async for Hardware wallets, but can be sync for the case where a software wallet stores and has direct access to the privateKey. 

However, to simplify development of this packages/library I'm building I want to work with the most... complex flow, the async flow, and nailing that makes the sync flow trivial. I do this by simply wrapping the sync singing flow in an async method, resulting in shared APIs between the two different flows.

So here comes TMI :) 

# Before use of `neverthrow`

```typescript
export type Signer = {
	/**
	 * Produces a cryptographic signature of the input.
	 *
	 * @param {UnsignedMessage} unsignedMessage - The unsigned message to be hashed and signed.
	 * @returns {Signature} An EC signature produces by this signer when signing the message.
	 */
	readonly sign: (
		unsignedMessage: UnsignedMessage,
	) => Promise<Signature>
}

const signWithIndutnyElliptic = (input: {
	readonly privateKey: UInt256
	readonly data: Buffer
}): Signature => {
	const secp256k1 = new ec('secp256k1')

	const privateKey = secp256k1.keyFromPrivate(input.privateKey.toString(16))

	const ellipticSignature = privateKey.sign(input.data, {
		canonical: true,
	})

	// 'uint256FromBN' can throw, uff, hmm wanna change this...
	const r = uint256FromBN(ellipticSignature.r)
	const s = uint256FromBN(ellipticSignature.s)

	return {
		r: rOrError,
		s: s,
	}
}

export const PrivateKey = (scalar: UInt256): Signer => {
	return {
		sign: async (
			unsignedMessage: UnsignedMessage,
		): Promise<Signature> => {
                         // Making something sync -> async
			return Promise.resolve(
					signWithIndutnyElliptic({
						privateKey: scalar,
						data: unsignedMessage.hasher(unsignedMessage.unhashed),
					})
				)
			)
		},
	}
}
```

# After, using `neverthrow`
Now we introduce `neverthrow` to propagate errors, using `Result` for sync and `ResultAsync` for async.

```typescript

export type Signer = {
	/**
	 * Produces a cryptographic signature of the input.
	 *
	 * @param {UnsignedMessage} unsignedMessage - The unsigned message to be hashed and signed.
	 * @returns {Signature} An EC signature produces by this signer when signing the message.
	 */
	readonly sign: (
		unsignedMessage: UnsignedMessage,
	) => ResultAsync<Signature, Error>
}

const signWithIndutnyElliptic = (input: {
	readonly privateKey: UInt256
	readonly data: Buffer
}): Result<Signature, Error> => {
	const secp256k1 = new ec('secp256k1')

	const privateKey = secp256k1.keyFromPrivate(input.privateKey.toString(16))

	const ellipticSignature = privateKey.sign(input.data, {
		canonical: true,
	})

       // 'uint256FromBN' now returns `Result<UInt256, Error>` instead of `UInt256` and throws.
	return combine([
		uint256FromBN(ellipticSignature.r),
		uint256FromBN(ellipticSignature.s),
	]).map((resultList) => {
		return {
			r: resultList[0],
			s: resultList[1],
		}
	})
}

const resultToAsync = <T, E>(
	result: Result<T, E>,
): ResultAsync<T, E> => {
	return result.asyncAndThen((value) => {
		return okAsync(value)
	})
}

export const PrivateKey = (scalar: UInt256): Signer => {
	return {
		sign: (
			unsignedMessage: UnsignedMessage,
		): ResultAsync<Signature, Error> => {
			return resultToAsync(
				signWithIndutnyElliptic({
					privateKey: scalar,
					data: unsignedMessage.hasher(unsignedMessage.unhashed),
				}),
			)
		},
	}
}

```

**Comment by supermacro** [comment]
@Sajjon what about using [`asyncMap`](https://github.com/supermacro/neverthrow#resultasyncmap-method)?

```typescript
const identity = <T>(val: T): T => val

export const resultToAsync = <T, E>(
	result: Result<T, E>,
): ResultAsync<T, E> => {
	return result.asyncMap(identity)
}
```

In fact, there's no need to have a `resultToAsync` function at all:

```typescript
myResult
  .map(doSomeSyncCryptoStuff)
  .andThen(doSomeSyncStuffThatMayFail)
  .asyncMap((val) => val) // now it's a ResultAsync
```

Lastly, you could also use [`asyncAndThen`](https://github.com/supermacro/neverthrow#resultasyncandthen-method) on the result to simultaneously:

- Do an async computation
- Convert the `Result` into a `ResultAsync`.

**Comment by paduc** [comment]
I fail to see the point of `Result` => `ResultAsync` as all methods that accept a `ResultAsync` also accept a `Result`.

**Comment by supermacro** [comment]
> I fail to see the point of Result => ResultAsync as all methods that accept a ResultAsync also accept a Result.

Not sure, just trying to find simple solutions for @Sajjon.

Going to close this issue.
