### ISSUE TITLE
Heterogeneous `combine` typing

### ISSUE THREAD

**Issue by wiktor-obrebski** [supermacro/neverthrow#224]
Hi. 
With my understanding, only typing stops `combine` currently from working with heterogeneous Results, implementation looks ready for them.
I just prepared types for `combine` that works for `Result` of many types, at least in my tests. Could it be useful for the library?

It will only works for TS 4.0+.

```ts

declare function combine<T extends Result<unknown, unknown>[]>(
    resultList: [...T]
  ): CombineResult<T, T>;


type CombineResult<T extends unknown[], U extends unknown[]> = T extends [
  infer Element,
  ...(infer Rest)
]
  ? Element extends Err<unknown, infer ErrH>
    ? Element
    : CombineResult<Rest, U>
  : Ok<
      { [Index in keyof U]: U[Index] extends Ok<infer OkElement, unknown> ? OkElement : never },
      unknown
    >;

**Comment by supermacro** [comment]
Hey @wiktor-obrebski,

You're correct. Only typings are preventing `combine` from being used on heterogenous lists.

Some more context / info: https://github.com/supermacro/neverthrow/issues/222#issuecomment-755528430

I did just try your types on `combine` but I am not getting the correct type information. See the following screenshot. 

<img width="1099" alt="Screen Shot 2021-01-11 at 11 52 07 AM" src="https://user-images.githubusercontent.com/10621548/104212692-79cc4f80-5403-11eb-9d50-96f9993e65b0.png">

I am trying to understand your `CombineResult` type before tying to modify it / play around with it. The multiple ternary expressions are throwing me off a bit, can you tell me if my understanding is correct so far?

```typescript
type CombineResult<T extends unknown[], U extends unknown[]> = T extends [
  infer Element,
  ...(infer Rest)
]
  ? Element extends Err<unknown, infer ErrH>
    ? Element
    : CombineResult<Rest, U>
  : Ok<
      { [Index in keyof U]: U[Index] extends Ok<infer OkElement, unknown> ? OkElement : never },
      unknown
    >;
```

- if `T` is a list containing at least one element, denoted by `Element` 
  - and if `Element` is an `Err` then return that `Element` as the type of `CombineResult`
  - else, recursively descend down the rest of the list
- else the list is an Ok where,
  - ????
  
I haven't yet understood / grokked the first type argument to `Ok`.

**Comment by wiktor-obrebski** [comment]
Interesting - your example do not work, but this works:
```ts
const list = combine([ok('123'), err(123)]);
```
looks like it is a tuple when provided directly, but an array when stored in a variable. I will try to find something to help with that soon. 

Your analyze is correct.
About the first type argument to `Ok`:
```ts
{ [Index in keyof U]: U[Index] extends Ok<infer OkElement, unknown> ? OkElement : never }
```
it's an array of all `Ok` object values.
the `never` in this definition should never happen if input list have only `Err` and `Ok` objects.

**Comment by wiktor-obrebski** [comment]
Ok, I did a lot of research this evening and I have new proposition for solution.

First I want to recognize two cases:
 1. We dealing with array types. Array types in typescript do not have defined length and type of every parameter - just one general type for every possible item. e.g. 
```ts
const resultList = [nt.ok('123'), nt.ok(123)]; 
// (Ok<string, unknown> | Ok<number, unknown>)[]
```
In this case we can only decide about general `Result<(T | U)[], W>` because we do not know if errors are in the array (the type `(Ok<string, unknown> | Ok<number, unknown>)[]` do not guarantee an error, just allow it). Additionally, we do not know how much items are in array. 

2. We dealing with tuples. Tuple have defined length and value for every parameter, e.g.
```ts
const resultList = [nt.ok('123'), nt.ok(123)] as const; 
// readonly [Ok<string, unknown>, Ok<number, unknown>]
```
In such case we have full data and we can decide about types clearly (return tuple `Result<[T, U], W>` instead of array).

My new proposition for typings, covering both cases (the one for tuples is similar like before):

```ts

declare function combine<T extends nt.Result<unknown, unknown>>(
  resultList: T[]
): ResultFromArray<T>;

declare function combine<T extends nt.Result<unknown, unknown>[]>(
    resultList: readonly [...T]
  ): ResultFromTuple<T, T>;


type ResultFromTuple<T extends unknown[], U extends unknown[]> = T extends [
  infer Element,
  ...(infer Rest)
]
  ? Element extends nt.Err<unknown, infer ErrH>
    ? Element
    : ResultFromTuple<Rest, U>
  : nt.Ok<
      { [Index in keyof U]: U[Index] extends nt.Ok<infer OkElement, unknown> ? OkElement : never },
      unknown
    >;

type ResultFromArray<T extends nt.Result<unknown, unknown>> = nt.Result<
  T extends nt.Ok<infer A, unknown> ? A[] : never,
  T extends nt.Err<unknown, infer B> ? B : never
>;
```

My tests for point 1:
```ts
const okResultList = [nt.ok('123'), nt.ok(123)];
const errResultList = [nt.ok('123'), nt.err(new class MyError {})];

const listOk = combine(okResultList);
// Result<(string | number>)[], never>

const listErr = combine(errResultList);
// Result<string[], MyError>
```

My tests for point 2:
```ts

const okTupleList = [nt.ok('123'), nt.ok(123)] as const;
const errTupleList = [nt.ok('123'), nt.err(new class MyError {})] as const;

const listOk = combine(okTupleList);
// Result<[string, number], never>

const listErr = combine(errTupleList);
// Result<never, MyError>
```

small pain: I was not able to force TypeScript to recognize proper function declaration for tuples without implicit `as const`:

```ts
...
// this works as with normal array version
const listOk = combine([nt.ok('123'), nt.ok(123)]);

// this works as tuple version
const listOk = combine([nt.ok('123'), nt.ok(123)] as const);
```

**Comment by paduc** [comment]
Awesome work @wiktor-obrebski !

I'm afraid the tuple version using `as const` will not work with non-const literal expression (such as results returned by functions).

I believe we're facing a case that is very similar to `Promise.all`, as @supermacro has noted in another thread. [This is the typescript Promise.all implementation](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es2015.promise.d.ts#L89) .

I wonder if typescript 4 allowed to change this implementation.

**Comment by wiktor-obrebski** [comment]
both declaration can work in the same time, typescript choose proper one related to input type.
about result of function, if the function return array, it will use array version, if it return tuple, it use tuple version. 

it's quite clear that 2 kinds of types are needed - often we have arrays that length is not known in compile time. in such case we need to determine types (if needed) in runtime. this is covered by first version.
but often we would want to just compose some results inline, e.g.

```ts
// this would be ideal, a and b strong typed
combine([nt.ok(456), nt.ok('123')]).map(
  ([a, b]) => a + parseInt(b)
);

// but with my implementation it would must work like this:
combine([nt.ok(456), nt.ok('123')] as const).map(
  ([a, b]) => a + parseInt(b)
);

```

**Comment by paduc** [comment]
@wiktor-obrebski Do you have a real use-case for combining a tuple of _const_ results ?

**Comment by wiktor-obrebski** [comment]
good question :P when I think about this now, I believe it's much more useful to handle cases for tuples where specific result type can be (in compile time) an ok and an error and we do not know this, e.g.

```ts
type ParseError = {msg: string};

type NumberResult = Result<number, ParseError>;

const test1: [NumberResult, NumberResult] = [ok(456), ok(123)];
const test2: [NumberResult, NumberResult] = [ok(456), err({msg: 'something happen'})];

const result1 = combineResults(test1);
const result2 = combineResults(test2);

function combineResults(results: [NumberResult, NumberResult]) {
  const combinedResult = combine(results)
  // combinedResult expected type would be: Result<[number, number], ParseError>

  return combinedResult.map(
    ([a, b]) => a + b
  ).mapErr(
    err => {
      console.log(err.msg);
      return 0;
    }
  );
}
```
`combinedResult` const expected type should be: `Result<[number, number], ParseError>`. It would be useful, more real e.g. 
```ts
const userResult: Result<User, NotFoundError> = fetchUser(userId);
const transactionResult: Result<Transaction, NotFoundError> = fetchTransaction(transactionId);

const isTransactionOwnerResult = combine([userResult, transactionResult)
  .map(([user, transaction]) => user.id === transaction.userId)
  .mapErr(err => {
      logger.error(err);
      return false;
  );
```

what do you think? I just starting to get experience with `neverthrow` and it's not clear for me what are most useful flows.

(types I pasted above are not ready for this usage, let's define first what is really expected)

**Comment by paduc** [comment]
Yes @wiktor-obrebski I agree that `Result`s are mostly useful when we don't know if it's a success or an error yet (which means we can't use `as const`).

Your last example is good example of a typical `neverthrow` flow: wrap low-level apis in functions returning `Result` or `ResultAsync`, combine/chain `Result`s all the way to the point where we unwrap it (in general, at the interface between the application and the outside world, e.g. express `res.send`, call to third-party api, ...).

**Comment by supermacro** [comment]
I've landed on the following type definition:

```typescript
type ExtractOkTypes<T extends Result<unknown, unknown>[]> = {
  [key in keyof T]: T[key] extends Result<infer U, unknown> ? U : never
}

type ExtractErrTypes<T extends Result<unknown, unknown>[]> = {
  [key in keyof T]: T[key] extends Result<unknown, infer E> ? E : never
}
```

This allows me to get all the `T` and `E` values in a tuple regardless of the size of the tuple. I'm just sharing what I have so far. I still need to test things out.

**Comment by supermacro** [comment]
So this approach did indeed work. Check out the implementation based on the most recent commit to the project:

https://github.com/supermacro/neverthrow/blob/cfd12a9af796b11426f9426fa94795912f103b77/src/utils.ts

**Comment by wiktor-obrebski** [comment]
this works good for tuples, like in my example - but do not work properly for direct usage of `ok` and `err` functions:
```ts
const test2 = [
  ok(456),
  err({ msg: 'something happen' }),
];
```

I noticed that this *would* work properly if the `ok` and `err` function would use `never` type instead of `unknown` for it's not used type. I mean `Ok<AType, never>` and `Err<never, AType>`.

**Comment by supermacro** [comment]
The `ok` and `err` functions use `E` and and `T` as ambient type variables that get "filled" depending on the context in which they are called. 

Example:

```typescript
const getUser = (): Result<User, DBError> => {
  // .. business logic
  return ok(user)
}
```

If we change `ok` and `err` to return `never` for the unused types then the above would not work. This would be a pretty big breaking change.

Example error:

<img width="1142" alt="Screen Shot 2021-01-12 at 12 49 20 PM" src="https://user-images.githubusercontent.com/10621548/104352408-a308e080-54d4-11eb-836d-021336f0a55f.png">

However, I **think** that in most situations folks will have lists where the `T` and `E` types are **not** `unknown`. This is an assumption right now. But if my assumption is true, then it's not that big of a concern that `combine` returns a `Result<unknown[], unknown>`. It should be a edge case that occurs infrequently. 

Also, logically, the type `Result<unknown[], unknown>` makes sense because all types (example: `string`) belong to the set / type `unknown` .. so `string | unknown` just becomes `unknown`.

**Comment by wiktor-obrebski** [comment]
I believe people typically would like to use type inference in many cases.
can not similar be found in real apps from time to time?

```ts
class Error {};
function fetchMe(someCondition: boolean) {
  if (someCondition) {
    return nt.ok('1234');
  } else {
    return nt.err(new Error());
  }
}

const res = testMe(true)
const res2 = testMe(false)
const comRes = combineResults([res, res2]);
// : nt.Result<unknow[], unknow>

// when you declare return type manually it will work like expected:
// function fetchMe(someCondition: boolean): Return<string, Error> {
```

**Comment by supermacro** [comment]
Ahh interesting, I would have thought that the inferred type of `fetchMe` would be `Result<string, Error>`. That's a bummer.

Well, as of now I don't know what would be a good solution. Changing the return type of `ok` to be `Result<T, never>` is not a good solution in my opinion because of the breaking change and the overhead required to make a `Result<T, never>` conform to some `Result<T, E>` (having to call `mapErr` on it).  And same issue with `err` being a `Result<never, E>`.

I'll have to do some more research on this. But I think for now it's a good improvement over the current implementation that only allows for homogeneous lists.

**Comment by wiktor-obrebski** [comment]
I agree that `never` is not good solution, it was just fast notice. I will look at it tomorrow too, I believe we are close to best fit solution.

**Comment by paduc** [comment]
I haven't tried it yet, but I believe @supermacro hinted that we could try an approach similar to the implementation of `Promise.all`. Maybe that would result in better typings ?

I don't have time right now to try it but I might in the next few days.

**Comment by Sajjon** [comment]
I need it now :D ship it? :)

**Comment by supermacro** [comment]
The typings approach implemented within `Promise.all` would lead to the same problem, albeit with a less generic solution (the size of the tuple is constrained by the amount of overloads we write manually). 

The second a concrete / known type is unioned on `unknown`, then the resulting type becomes `unknown`.

I don't know if this is a solvable problem unfortunately 😢.

Regardless, I will ship the current state of `neverthrow` today. Improvements can come in a later release.

**Comment by supermacro** [comment]
Closing this issue, but as always feel free to open a new issue if there's something you want to discuss / improve / provide feedback on!
