### ISSUE TITLE
Question: How to recover from an error result to an ok result dynamically?

### ISSUE THREAD

**Issue by wiktor-obrebski** [supermacro/neverthrow#225]
I see that I can map an ok value to any result I want by using `.andThen`.
I can use `unwrapOr` to replace every error by given value.

But what about mapping an error value to an ok value dymically? It's sound quite useful that we want to recover after error and e.g. provide a default value for one type of error and left error as is for other type.

e.g.
```ts
const occupationResult: Result<string, NotFoundError | ConnectionError> = await getUserOccupation();

const safeOccupationResult = occupationResult.someErrorMappingFunction(
  (error: NotFoundError | ConnectionError) => {
    if (err instanceof NotFoundError) {
      return ok("User not found");
    } else {
      return error;
    }
  }
);


// comparison to promises:
// a - rejected promise
const a = Promise.reject("an error");
// b - resolved promise
const b = a.catch(err => 33);
// c - rejected promise
const c = a.catch(err => Promise.reject("other error"));
```

how I could achieve currently the result that my imaginary function `someErrorMappingFunction` do?

**Comment by paduc** [comment]
I've had the same use-case in mind for quite a while. I guess we could call it `orElse` (as the opposite as `andThen`). It would take the error case and call a function that returns a `Result`.

What I have been doing for now, is (ab)using `match`.

```typescript
result.match((value) => ok(value), (err) => (err instanceof NotFoundError) ? ok("User not found") : err(error))
```

**Comment by supermacro** [comment]
Sounds like there's a need for a `orElse` function.

I'm working on neverthrow today, so I'll make sure to implement a `orElse` method on both `Result` and `ResultAsync`.

**Comment by wiktor-obrebski** [comment]
Did you consider to make `map` and `mapErr` more general?
Promises have just 2 functions, `then` and `catch`.
If I return a promise in `then` or `catch` callback, it will resolve/reject the returned promise.
But if I return any other value than a promise, it's is assumed that I want to resolve promise with given literal value - so it's just shortcut for `Promise.resolve(value)`.

I am writing about this because I believe that a smaller API is better. Bigger APIs for libraries make them more chaotic and hard to use, IMHO. The solution used in promises API is quite intuitive - at least for JS/TS experienced developers.

**Comment by wiktor-obrebski** [comment]
addiotionally, the names `andThen` and `orElse`are not such clear as `map` and `mapErr` IMO.

**Comment by supermacro** [comment]
> Did you consider to make map and mapErr more general?

For `ResultAsync`, most functions accept either some synchronous value (like `123`) or a value inside of a `ResultAsync` (like `okAsync(123)`), thus reflecting the same style of api as the Promise api. 

> But if I return any other value than a promise, it's is assumed that I want to resolve promise with given literal value - so it's just shortcut for Promise.resolve(value).

Yup this is exactly how `ResultAsync` behaves as well.

... However the above does not apply for `Result`s at the moment and I am not sure if it's worth it. The way it would work is by having overloads on all Result methods. Example for `Result.map`:

```typescript
  map<A>(f: (t: T) => ResultAsync<A, E>): ResultAsync<A, E>;
  map<A>(f: (t: T) => A): Result<A, E> {
    return ok(f(this.value))
  }
```

Nonetheless I agree that smaller apis are better! So I am open to suggestions / ideas.

---- 

> additionally the names andThen and orElse are not such clear as map and mapErr IMO.

I'm thinking about a better name for `orElse` at the moment 🤔. Maybe ... `recover`?

**Comment by paduc** [comment]
I'm not sure I like the idea of having `map` and `mapErr` accept callbacks returning `Result`s. The point of `map` and `mapErr` is that they do not change the nature of the `Result` (an `Ok` remains an `Ok`, an `Err` remains an `Err`), they should only transform the value itself.

Promises are a bit different in that they auto-unwrap (`Promise<Promise<T>>` becomes a `Promise<T>`) which is possible because they do not handle the error case. 

That's why I believe `Result` should have distinct `map` `mapErr` `andThen` and `orElse` as they all have a very specific transformation purpose. This is not specific to `neverthrow`, we find the same distinct methods in most (all?) monad libs that have a `Either` type.

**Comment by paduc** [comment]
The pseudo-signatures of the four transformations would look like this:

```ts
Result<T,E>.map( T => U ) => Result<U, E> // transform the value of Ok case
Result<T,E>.mapErr( E => F ) => Result<T, F>  // transform the value of Err case
Result<T,E>.andThen( T => Result<U, E> ) => Result<U, E> // chain next command after Ok case
Result<T,E>.orElse( E => Result<U, E> ) => Result<U, E> // chain next command after Err case

**Comment by wiktor-obrebski** [comment]
with my understanding both - `andThen` and `orElse` should be able to return any new result - with new value or with new error.
if yes, the typings are not correct. It should be rather:
```ts
Result<T,E>.andThen( T => Result<U, F> ) => Result<U, F> // chain next command after Ok case
Result<T,E>.orElse( E => Result<U, F> ) => Result<U, F> // chain next command after Err case
```
is not it?

I see that currently this do not give me proper types (but give me proper value):
```ts
const result = nt.ok(1234);
const wynik = X2.andThen(val => {
  return nt.err(val + 1);
});

**Comment by supermacro** [comment]
`andThen` and `orElse` are inverses of each other.

```
  Result<T, E>.andThen<U>(_f: (t: T) => Result<U, E>): Result<U, E>;

  Result<T,E>.orElse<A>(_f: (e: E) => Result<T, A>): Result<T, A>;
```

I don't really buy the argument that they should freely return a brand new Result given the above allow you to map both `T` and `E` as you wish. I don't see a practical use case for loosening that restriction.

**Comment by paduc** [comment]
For the moment, `neverthrow` does not allow to chain `Result`s with different error types (see issue #30 ).

**Comment by paduc** [comment]
If it did, then the correct types would be:

```ts
Result<T,E>.andThen( T => Result<U, F> ) => Result<U, E | F> // chain next command after Ok case
Result<T,E>.orElse( E => Result<U, F> ) => Result<U, E | F> // chain next command after Err case
```

**Comment by supermacro** [comment]
`orElse` is now implemented:

https://github.com/supermacro/neverthrow#resultorelse-method

Closing the issue to keep things a bit tidy, but feel free to chat here or in a new issue.
