### ISSUE TITLE
How about using Promise<Result> as ResultAsync?

### ISSUE THREAD

**Issue by LongOddCode** [supermacro/neverthrow#227]
Hi, according to [issue](https://github.com/microsoft/TypeScript/issues/5911), why don't we use `Promise<Result>` as `ResultAsync`?

**Comment by supermacro** [comment]
Here's an example:

https://github.com/parlez-vous/server/blob/2496bacf55a2acbebc30631b5562f34272794d76/src/routes/embed/get-comments.ts#L69

The above is asynchronous, but I am chaining operations on the async result without having to actually unwrap the `Promise`. `ResultAsync` is PromiseLike which means it is a `Promise` **and** it has a bunch of useful methods. The only downside is that you can't declare a function as `async` if it returns a `ResultAsync`.

The above example would be a lot more verbose if I had to keep `await`ing the promise or calling `.then` on the promise and **then` calling the `andThen` methods.
