### ISSUE TITLE
Console Warning from combineResultAsyncList()

### ISSUE THREAD

**Issue by HyperCharlie** [supermacro/neverthrow#238]
I am getting a console warning from Neverthrow that is probably familiar:

[neverthrow] - `fromPromise` called without a promise rejection handler - Ensure that you are catching promise rejections yourself, or pass a second argument to `fromPromise` to convert a caught exception into an `Err` instance

However, it is being generated from inside neverthrow itself. It seems to be coming from the method combineResultAsyncList(), line 344-ish. Looks like we need a proper error handler method on there!

**Comment by supermacro** [comment]
Hey @HyperCharlie,

This annoying little side effect was removed in January. See the following release:

https://github.com/supermacro/neverthrow/releases/tag/v4.0.0

Please upgrade your `neverthrow` version to >= v4
