### ISSUE TITLE
How to avoid "callback-hell" type of syntax?

### ISSUE THREAD

**Issue by rhlsthrm** [supermacro/neverthrow#239]
I am looking into this library. However I can't seem to understand how I would avoid nesting `.map`s inside each other.

For example, I would do something like:
```ts
asyncOperation1.map(success1 => {
  console.log("cool: ", success1);
  asyncOperation2.map(success2 => {
    console.log("cool: ", success2);
    asyncOperation3.map(success3 => {
      ...
    }).mapErr(err => {
      console.log("uh oh", err);
    });
  }).mapErr(err => {
    console.log("uh oh", err);
  });
.mapErr(err => {
  console.log("uh oh", err);
});
```

I feel like I must be missing something but I haven't seen any examples addressing this case, of multiple async operations that depend on previous results. Any links to examples or suggestions for this?

**Comment by paduc** [comment]
Hello @rhlsthrm !

When chaining multiple operations, you would do something similar to a chain of `Promise`s.

```typescript
const result = asyncOperation1.andThen(asyncOperation2).andThen(asyncOperation3)
```

The error case can be handled at the very end of the chain using `.match` or `isErr()` and `.error`.

```typescript
const result = await asyncOperation1.andThen(asyncOperation2).andThen(asyncOperation3)
if(result.isErr()){
  console.error(result.error)
}
else{
  console.log('Success', result.value)
}

// or
await asyncOperation1.andThen(asyncOperation2).match((value) => console.log('success', value), (error) => console.error(error))
```

I personally make web apps, and use `ResultAsync` everywhere in my app but only use `.match` in my controllers, where I unwrap the final `ResultAsync` and decide what to do in the different error cases (because there are several error types) and the success case.


[Here is a live production example](https://github.com/MTES-MCT/potentiel/blob/master/src/controllers/project/getCancelInvitationToProject.ts#L24) of a controller unwrapping the value/error cases.

**Comment by paduc** [comment]
By the way, `.map` is a method used to transform a value into another value (not to unwrap the value of a `Result) and `.mapErr` is used to transform an error into another error (not to unwrap the error).
You would not use them to `console.log` the different cases.

**Comment by rhlsthrm** [comment]
@paduc thank you very much! I was misunderstanding the case of `map` it seems. I will give this a look and I will reach out if I have more questions!

**Comment by rhlsthrm** [comment]
For reference, I more or less wrote a version of this library myself (very rudimentary). I find myself constantly doing things like:

```ts
const res = await doSomething();
if (res.isError) {
  return Result.fail(res.getError());
}

const res2 = doSomethingElse(res.getValue());
if (res2.isError) {
  return Result.fail(res.getError());
}
```

This works and I don't throw and catch but it's rather tedius. I feel like there is a better approach and that's how I came across this library. I was thinking `.map` and `.mapErr` would do what I need, but it seems I'm misunderstanding. Any more light you can shine for me given my above example? Basically I do need to unwrap results and do more ResultAsync operations. It seems like I need to use `match` in this case?

**Comment by paduc** [comment]
@rhlsthrm I believe you tend to unwrap the result too early. A more idiomatic approach is to keep the result wrapped for as long as possible and use `.andThen` to chain each successive operation.

```ts
const res = doSomething(); // res is ResultAsync<T1,E1>
const res2 = res.andThen(doSomethingElse) // res2 is ResultAsync<T2, E1 | E2>
// ... later on, call match

// or more simply
const res = doSomething().andThen(doSomethingElse)
```

It really behaves like a `Promise` in that, you can chose to `await` right away or chain it with `.then` and keep it as a promise. The difference is that the error case is typed and it's a lot harder to forget to handle it.

A good indicator that you are using `neverthrow` correctly is that you use `andThen` way more often than `isOk/isError/match`.
