### ISSUE TITLE
TODO: trasition over to CircleCI

### ISSUE THREAD

**Issue by supermacro** [supermacro/neverthrow#241]
CI Checks have stopped working on travis. I personally know / understand Circle more so I figured it would be worth the investment to just switch over to CircleCI.

.... i'll get around to this when I get a chance 🙂 

But in the mean time, **if you are submitting a contribution** be sure to run `typecheck` + `lint` + `test` npm scripts!

**Comment by Liam-Tait** [comment]
I am familiar with setting up github actions if that would be an option?

**Comment by supermacro** [comment]
Thank you @Liam-Tait but I am too much of a CircleCI fanboy 😄

**Comment by supermacro** [comment]
Done 🚀 

- e6b284f39431c50373dc1dddf90e35b8fd194049
- 56578820330a366cf0a58421628f10c3dc9af5bc
