### ISSUE TITLE
Let ResultAsync.fromPromise() accept PromiseLike

### ISSUE THREAD

**Issue by Roxas92** [supermacro/neverthrow#249]
I'm currently working on a Vue 3 project came accross with a Task/Concurrency-Library (https://vue-concurrency.netlify.app/).

Performing a task (`taskName.perform()`) return a `TaskInstance`. When I understood correctly `TaskInstance` implements `PromiseLike`. (https://github.com/MartinMalinda/vue-concurrency/blob/559496a384819979df23fcb24e5e28765ee7638a/src/TaskInstance.ts#L19)

So I tried if it's possible to do something like `ResultAsync.fromPromise(task, err)`. But TypeScript keeps telling me

```
Property '[Symbol.toStringTag]' is missing in type 'TaskInstance<Result<LessonSearchResponse, Error>>' but required in type 'Promise<unknown>'
```

So I was wondering if it might be possible to either extend `ResultAsync.fromPromise()` to accept `PromiseLike` or to introduce a new method like `ResultAsync.fromPromiseLike()`.

**Comment by supermacro** [comment]
Hey @Roxas92,

Thanks for opening this issue. The issue I see with accepting anything that is `PromiseLike` means that there has to be a dedicated implementation for how to actually unwrap the inner value so as to create a `ResultAsync<T, E>` from it. 

In the casee of `TaskInstance` it looks like the implementation would require some sort of polling mechanism.

So given that there is no generic way to handle all `PromiseLike` values, I would recommend creating your own implementation that takes a `TaskInstance<T>` and returns a `ResultAsync<T, E>`.

**Comment by paduc** [comment]
I wonder if we could change the signature of `fromPromise` to:
```ts
static fromPromise<T, E>(promise: PromiseLike<T>, errorFn: (e: unknown) => E): ResultAsync<T, E>
```

**Comment by supermacro** [comment]
Took me a while to get around to this. If this is a non-breaking change I am open to contributions @Roxas92
