### ISSUE TITLE
Generate documentation based on inline function documentation

### ISSUE THREAD

**Issue by Liam-Tait** [supermacro/neverthrow#250]
Idea originating from this comment
https://github.com/supermacro/neverthrow/pull/248#issuecomment-795512200
> If we adhere to tsdoc syntax, then it may be possible to generate the README docs based off of these docs, thus eliminating the duplication of documentation... but this is for another day. — @supermacro 

To me the requirements would be that:

- docs are still available in `README.md`
- docs contain the same information as the current `README.md`

**Comment by supermacro** [comment]
Yes, exactly. `README` would mirror what's in the tsdoc documentation.

**Comment by supermacro** [comment]
As cool as this sounds, the surface area of this codebase does not really get much added benefit from this functionality. Maybe one day I'll get around to this haha
