### ISSUE TITLE
Error types are incompatible

### ISSUE THREAD

**Issue by DanielSWolf** [supermacro/neverthrow#252]
Consider the following example. On error, both function `foo` and function `bar` return an `Err` object that holds an `Error`. So I would consider the `Err` objects returned by the two functions to be interchangeable: When `bar` calls `foo` and receives an error, I'd expect `bar` to be able to just forward that error.

```ts
function foo(): Result<number, Error> {
  return err(new Error('test'));
}

function bar(): Result<string, Error> {
  const result = foo();

  // Doesn't work:
  // Type 'Err<number, Error>' is not assignable to type 'Err<string, Error>'.
  if (result.isErr()) return result;

  return ok('test');
}
```

In practice, however, TypeScript complains that "'Err<number, Error>' is not assignable to type 'Err<string, Error>'".

What's the best practice for forwarding errors that already wrap a value of the correct type?

**Comment by paduc** [comment]
Hello @DanielSWolf !

Indeed, the result returned by `foo()` does not have the same type as the return type of `bar()` so you cannot forward it as is.

However, since you know it’s an error, you can unwrap the error and re-wrap it into a `Result<string, Error>`.
```ts
if(result.isErr()) return err(result.error);
```

**Comment by DanielSWolf** [comment]
Thanks for the explanation! The first option solves my immediate problem, but I'll certainly experiment with chaining.
