### ISSUE TITLE
ResultAsync.map and Result.asyncMap README link conflict

### ISSUE THREAD

**Issue by tobloef** [supermacro/neverthrow#253]
When you click the "`ResultAsync.map` (method)" link you go to the "`Result.asyncMap` (method)" header. This is because the url for the two headers in the ToC is the same. Not sure how to fix it.

**Comment by supermacro** [comment]
Fixed here:

https://github.com/supermacro/neverthrow/commit/99d5111f950208dddff9e6f85182d2cfbae7828b

Thanks for pointing this out!

I'll be releasing this + #251 momentarily.
