### ISSUE TITLE
Feature request - Expose finally in ResultAsync

### ISSUE THREAD

**Issue by jhasselgren** [supermacro/neverthrow#254]
Hi and really good work with this library, really like it!!!

It would be great if ResultAsync could expose the finally method on a promise. The use case I have is that I am using tracing and the last thing I need to do in each function (that is traced) is to close the span.

Right now I am doing something like this:

```typescript
const apiCall = (): ResultAsync {
    return new ResultAsync(actualApiCall) 
}


const actualApiCall = async (): Promise<Result> {
  const span = this.tracer.startSpan('delivery-parameters-api: calcParameters');
  try {
    return await ResultAsync.fromPromise()
  }
  finally{
    span.end()
  }
}
```

if finally would be expose I could write the same code like this:

```typescript
const apiCall = async (): ResultAsync {
  const span = this.tracer.startSpan('delivery-parameters-api: calcParameters');
  return await ResultAsync.fromPromise().finally(() => span.end())
}
```

**Comment by paduc** [comment]
Hello @jhasselgren !

Could you not use the `finally` on the promise itself ?

```ts
const apiCall = (): ResultAsync<T,E> => {
   const myPromise  = callSomeApi()
   myPromise.finally(() => { /* wrap things up */ })
   return ResultAsync.fromPromise(myPromise)
}
```

By the way, you cannot return a `ResultAsync` from an `async` method because the return type would be `Promise<ResultAsync>`.

**Comment by jhasselgren** [comment]
Not sure if that would work, that would result in that the closing of the trace (in this case)  is trigger when the api call is done, but the goal is that the trace should be closed when the entire chain is completed. For example if you have a heavy parsing that should be done on the response.

**Comment by paduc** [comment]
Could you maybe give a working example of what you would like to address ?

**Comment by jhasselgren** [comment]
https://replit.com/@jhasselgren/neverthrow-finish (tried to mimic how you create a span in @opentelemetry/api)

So think the solution could look something like this:
```Typescript
finally<A, B>(callback?: () => void): PromiseLike<A | B> {
   return new ResultAsync(this._promise.finally(res))
}
```

**Comment by paduc** [comment]
First of all, your uses of `new ResultAsync(promise)` should be replaced by `ResultAsync.fromPromise(promise)` or `ResultAsync.fromSafePromise` if you are absolutely sure that the promise does not throw.

I think I see what your are trying to achieve. You want to execute some code after a chain of `ResultAsync`, just like you would after a chain of `Promise`s. 

For a `Promise`, `finally` is useful to chain a callback that will execute if the `Promise` is successful or throws. However a`ResultAsync` acts like a `Promise<Result>` which never throws. This means that the throw case does not need to be handled and also that the `finally` callback would be executed in the same case as  `then`, and therefor adds nothing.

So you can use `then` instead of `finally` to achieve what you want.

```ts
const myResultAsync = doWork();

myResultAsync.then((res) => {
   // This code will always be executed
})

// or using await
const res = await myResultAsync;
// no need for try/catch/finally because ResultAsync never throws
```

**Comment by jhasselgren** [comment]
A big difference between finally and then is that `finally` do not return a new promise while `then` do.

In this case `then` also change object type, I get a promise instead of ResultAsync (which is really nice to work with and gives clean code). So I really want my function to return a ResultAsync object.

I have updated my example with how I would like my code should look like (do not have the finally code in that) and how I need to do now to add the finally code (in example2.ts)

This is also why I use `new ResultAsync()` instead of fromPromise  and fromSafePromise which more fells like to handle a "default" promise and not a Promise<Result> object. If I use fromPromise  or fromSafePromise on a Promise<Result> it looks like I lose the type info for the Error and also need to flatten the object.

**Comment by paduc** [comment]
With the `ResultAsync` type, I believe you never need to use `Promise<Result>`. 

The idiomatic way of using `neverthrow` is to use `Result` / `ResultAsync` everywhere in your call stack, using only sync functions and thus avoiding all `await/async`, except at the point you want to unwrap your `ResultAsync` (in your example, that would be in your `main()` function).
Naturally, you still have to handle `Promises` at the points you call third-party or native functions that return a `Promise`. For this, you would use `fromPromise` and provide a second callback for the error case. 

In your `example2.ts`, the `apiCall` should look like this (including finally statement):
```ts
const apiCall = (): ResultAsync<string, Error> => {
  const promise = new Promise((res) => {
    setTimeout(() => {
      console.log(`api work`);
      return res('api result');
    }, 200);
  })

  promise.finally(() => {
    console.log('Need to do something last');
  })

  return ResultAsync.fromPromise(
    promise,
    () => new Error()
  );
};
```

Same thing for your `myService` function:
```ts
const myService = async () => {
  return apiCall()
    .andThen(() => dbCall())
    // Chain other operations andThen/orElse/map/mapErr as you like
    .map(() => {
      console.log('service work');
      return 'service result';
    });
};
```

And then in your main, you can unwrap the `ResultAsync` and handle success and error cases:
```ts
const main = async () => {
  await myService().match(() => {
    console.log('Everythin is ok');
  }, (e) => {
    console.log('Something is wrong, you need to handle it');
  })
};
```

`finally` is used to execute a side effect (no value transformation).
If it's on the initial promise, you can use `.finally` on the promise before wrapping it using `ResultAsync.fromPromise`.
If it's on the whole chain, you can call it after awaiting your `ResultAsync`.
If it's in the middle of the chain, you can insert your side-effect in `map/mapErr` or `andThen/orElse`.

Which case would be inefficient for you ?

**Comment by supermacro** [comment]
> A big difference between finally and then is that finally do not return a new promise while then do.

Hmm, I don't think that's correct @jhasselgren 

[From MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally):

![Screen Shot 2021-04-21 at 1 40 35 PM](https://user-images.githubusercontent.com/10621548/115597478-4ffab280-a2a7-11eb-9bd5-9bf6927b3f30.png)

----

Regardless, I will close this issue soon if I don't hear back from you @jhasselgren

**Comment by supermacro** [comment]
Closing now. Feel free to comment / request to re-open @jhasselgren.
