### ISSUE TITLE
Using ResultAsync with async-await

### ISSUE THREAD

**Issue by davazp** [supermacro/neverthrow#258]
Hi,

I have been exploring different libraries to encode errors in my application.   There was one feature I really liked from `purify-ts`, and I implemented on top of fp-ts and neverthrow itself.  So I would like to share it in case others find it useful.

I am insterested in keep using async/await.  And have handled errors with a Result but ocasionally allow throwing for unexpected/fatal errors.

For that, there is a helper function that allows you to extract the 'ok' values automatically and propagate errors as async-await does, like it follows:

```typescript
    const f = await Do(async ({ fromPromise, throwE }) => {
       const x = await fromPromise(Promise.resolve(ok(3)))  //  x is 3,  not ok(3)!
       await fromPromise(Promise.resolve(err('fail')));      // never returns,  makes `f`  a Err.
       throwE(err('fail'));    // same, as before
       return 5;
    });
```

I like this approach because it allows me to use Result in a way that almost doesn't change the code.  

I could extend this to work with ResultAsync rather than `Promise<Result<T,E>>` if #257 is clarified.  Is this something that could be useful in the library?

Thanks!

## Full prototype

```typescript
import { err, ok, Result, ResultAsync } from "neverthrow";

const INTERNAL_THROW = Symbol("INTERNAL_THROW");

export interface AsyncHelpers<E> {
  fromPromise<T>(
    resultAsync: ResultAsync<T, E> | Promise<Result<T, E>>
  ): Promise<T>;

  throwE(err: E): never;
}

export function Do<T, E>(
  fn: (helpers: AsyncHelpers<E>) => Promise<T>
): Promise<Result<T, E>> {
  function throwE(err: E): never {
    throw {
      INTERNAL_THROW,
      error: err,
    };
  }

  async function fromPromise<T>(promise: Promise<Result<T, E>>) {
    const result = await promise;
    if (result.isOk()) {
      return result.value;
    } else {
      throwE(result.error);
    }
  }

  const helpers: AsyncHelpers<E> = {
    fromPromise,
    throwE,
  };

  return fn(helpers)
    .then((result) => ok<T, E>(result))
    .catch((e) => {
      if (e.INTERNAL_THROW === INTERNAL_THROW) {
        return err(e.error as E);
      } else {
        return Promise.reject(e);
      }
    });
}
```

**Comment by supermacro** [comment]
I would say that this pattern is a great thing for people to be aware of - but it's not necessarily something that should be added as part of the library. Therefore, a wiki article would be great. Or if you're much into blogging, a blog post would be awesome.

**Comment by davazp** [comment]
Fair enough.  I'll close the issue :-)  I'll keep in mind the idea of blogging about it after I get some experience using the pattern 👍
