### ISSUE TITLE
fromThrowable type signature too restrictive?

### ISSUE THREAD

**Issue by universalhandle** [supermacro/neverthrow#300]
Hello!

I think I've found a bug in neverthrow 4.2.1.

With this code, more or less lifted from the [documentation](https://github.com/supermacro/neverthrow#resultfromthrowable-static-class-method):

```ts
import { Result } from "neverthrow";

const foo = Result.fromThrowable(JSON.parse, () => {});
```

... I get this transpilation failure:

```
Argument of type '(text: string, reviver?: ((this: any, key: string, value: any) => any) | undefined) => any' is not assignable to parameter of type '(...args: readonly unknown[]) => any'.
  Types of parameters 'text' and 'args' are incompatible.
    Type 'unknown' is not assignable to type 'string'.ts(2345)
```

I haven't really dug in yet, but at first blush it seems like `fromThrowable` might be too opinionated about the arguments of the wrapped function.

It does seem to work to change the type signature of `fromThrowable` from:
`<Fn extends (...args: readonly unknown[]) => any, E>`
... to...
`<Fn extends (...args: readonly any[]) => any, E>`

Any thoughts?

**Comment by supermacro** [comment]
Hey @universalhandle,

Yes it indeed looks like a bug. I'm in agreement with your solution and always very appreciative of a Pull Request (with a test to prevent this regression!) 🙂

**Comment by universalhandle** [comment]
I can do that but am about to go on leave for a few days, so it'll have to be next week.

I'm not sure how to write tests around a type change like this... the best I can come up with is to just write a test which trivially implements `fromThrowable`. The test will fail to compile (and hence fail) if the function's type doesn't allow the arguments. It looks like the current tests for `fromThrowable` wrap a function which takes no arguments, which the type as currently written does allow. So, adding another case where the wrapped function actually takes arguments should do it, and I can certainly do that.

Please let me know if you had something else in mind.
