### ISSUE TITLE
Best way to get previous values?

### ISSUE THREAD

**Issue by tobloef** [supermacro/neverthrow#301]
Suppose I had a long chain of result calls, like the example below. What would be the best way to go about getting the previous values later in the chain?

```TypeScript
const doSomething = (): ResultAsync<T, E> => {
  return ResultAsync.fromPromise(...)
    .map((a) => aToB(a))
    .andThen((b) => useB(b))
    .map((c) => cToD(c))
    .andThen((d) => {
      // How can I get a, b, and c here nicely?
      console.log(`Did something with a (${a}), b (${b}), and c (${c}) to make d ${d}.`);
      return d;
    })
}
```

I was thinking I might be able to do something like the snippet below, but this is problematic because the code is asynchronous. Even if it wasn't, the type inference wouldn't recognize the results as being Ok afaik.

```TypeScript
const doSomething = (): ResultAsync<T, E> => {
  const aResult = ResultAsync.fromPromise(...);
  const bResult = aResult.map((a) => aToB(a));
  const cResult = bResult.andThen((b) => useB(b));
    
  return cResult
    .map((c) => cToD(c))  
    .andThen((d) => {
      console.log(`Did something with a (${a}), b (${b}), and c (${c}) to make d ${d}.`);
      return d;
    })
}
```

Another option would be to combine the new result with the previous in an array, like in the snippet below.

```TypeScript
const doSomething = (): ResultAsync<T, E> => {
  return ResultAsync.fromPromise(...)
    .andThen((a) => combine([okAsync(a), aToB(a)]))
    .andThen(([a, b]) => combine([okAsync(a), okAsync(b), useB(b)]))
    .map(([a, b, c]) => combine([okAsync(a), okAsync(b), okAsync(c), cToD(c)]))
    .map(([a, b, c, d]) => {
      console.log(`Did something with a (${a}), b (${b}), and c (${c}) to make d ${d}.`);
      return d;
    })
}
```

But this creates a lot of boilerplate, especially since the type inference (of `ExtractOkTypes` maybe?) isn't actually smart enough to work without explicitly specifying the generic type of `combine`. I left this out of the snippet, but suffice to say that it's quite cumbersome.

So, what would you recommend? This is trivial with normal async/await code, but I would rather not lose the type security from neverthrow.

**Comment by supermacro** [comment]
Linking https://github.com/supermacro/neverthrow/issues/186 to be organized. I'd say check that issue out, but there's not much new in there.

It's late right now where I'm at. So I'll put a bit more thought into this in the coming days.

**Comment by paduc** [comment]
Here's how I do it (using what's available):

```typescript
const doSomething = (): ResultAsync<T, E> => {
  return ResultAsync.fromPromise(...)
    .map((a) => ({ b: aToB(a), a }))
    .andThen(({a, b}) => useB(b).map((c) => ({ a, b, c }))
    .map(({ a, b, c }) => ({ a, b, c, d: cToD(c)}))
    .andThen(({a, b, c, d}) => {
      console.log(`Did something with a (${a}), b (${b}), and c (${c}) to make d ${d}.`);
      return d;
    })
}
```

**Comment by supermacro** [comment]
Closing this issue as it seems to me like @paduc's suggestiong is a good solution
