### ISSUE TITLE
[VsCode TypeError] Property value/error doesn't exist in Result

### ISSUE THREAD

**Issue by sanchaymittal** [supermacro/neverthrow#315]
TypeError in VsCode, Build doesn't error but it's annoying keep seeing these errors in vsCode.

## Problem
Property 'error' does not exist on type 'Ok<Success Type, Error Type>'
Property 'error' does not exist on type 'Result<Success Type, Error Type>'

Property 'value' does not exist on type 'Ok<Success Type, Error Type>'
Property 'value' does not exist on type 'Result<Success Type, Error Type>'

**Comment by supermacro** [comment]
Hey @sanchaymittal,

Thanks for informing me about this issue. Can you provide a reproducible example? Or perhaps a video recording using [Loom](https://loom.com)? Or steps to reproduce myself?

I could not reproduce the problem on VSCode Version: 1.58.1.

<img width="655" alt="Screen Shot 2021-07-22 at 11 28 00 AM" src="https://user-images.githubusercontent.com/10621548/126665877-36792249-48ed-483e-9149-67f8af705ae3.png">

**Comment by supermacro** [comment]
cc @rhlsthrm

**Comment by rhlsthrm** [comment]
This was actually our fault, we didnt realize we need to check it in an `if (res.isOk()) {` branch.

**Comment by sanchaymittal** [comment]
Yes, I was using this out of scope. That must be the reason for the typeError.

Thanks for quick response @supermacro
