### ISSUE TITLE
Combine types not inferred properly for homogenous ResultAsync list

### ISSUE THREAD

**Issue by rhlsthrm** [supermacro/neverthrow#316]
I have code similar to the following:

```ts
result.andThen(value => {
  // ...
  return combine([
    ResultAsync.fromPromise(
      getBalance(senderAddress), // returns Promise<BigNumber>
      (err) => new Error(...),
    ),
    ResultAsync.fromPromise(
      getBalance(receiverAddress), // returns Promise<BigNumber>
      (err) => new Error(...),
    ),
  ]);
}).andThen(([senderBalance, receiverBalance]) => {
  // senderBalance and receiverBalance should both be typed as BigNumber
});
```

When I try this code, I get type errors:
```
Argument of type '([senderBalance, receiverBalance]: [any, any]) => ResultAsync<unknown, HandlerError> | ResultAsync<undefined, unknown>' is not assignable to parameter of type '(t: unknown) => Result<unknown, unknown> | ResultAsync<unknown, unknown>'.
  Types of parameters '__0' and 't' are incompatible.
    Type 'unknown' is not assignable to type '[any, any]'.ts(2345)
```

Am I doing something wrong? If I change the last `andThen` to the following it works:

```ts
.andThen((balances) => {
  const [senderBalance, receiverBalance] = balances as BigNumber[];
  // ...
});
```

I don't believe I should have to cast it since the combine should give me the proper result with an array of values.

**Comment by supermacro** [comment]
This is a known issue which I have not had the time to address ... #226 provides some (somewhat outdated) context on the problem. [This comment](https://github.com/supermacro/neverthrow/issues/226#issuecomment-762227351) summarizes the discussion. 

I am open to addressing the issue (given I have time, or someone else is able to address this sooner than me) under a MAJOR change for the package.

----

Anyways, the current way that I work around this "limitation" is to declare lists as `const` so as the turn them into tuples.  

```typescript
  return combine([
    ResultAsync.fromPromise(
      getBalance(senderAddress), // returns Promise<BigNumber>
      (err) => new Error(...),
    ),
    ResultAsync.fromPromise(
      getBalance(receiverAddress), // returns Promise<BigNumber>
      (err) => new Error(...),
    ),
  ] as const);
```


Here is another example:

```typescript
  return combine([
    functionThatReturnsOneResultAsync(arg1),
    functionThatReturnsDifferentResultAsync(arg2),
  ] as const)

```

**Comment by supermacro** [comment]
Info on "const assertions":

**Comment by supermacro** [comment]
One thing I missed for your example is that `getBalance(senderAddress) and `getBalance(receiverAddress)` both return `Promise<BigNumber>` ... so you should have a `ResultAsync<BigNumber, Error>[]`.

I would definitely classify this as a bug. I'm a bit confused as to why that is occurring. 

### Attempt To Reproduce

I tried reproducing your issue using version `4.2.1`:

<img width="913" alt="Screen Shot 2021-07-22 at 4 04 19 PM" src="https://user-images.githubusercontent.com/10621548/126702511-d5f7f98e-d351-4904-9ac6-361b40600c34.png">

But as you can see I was not able to reproduce. 

This is the tsconfig I used:

```
{
  "compilerOptions": {
      "module": "CommonJS",
      "noImplicitAny": true,
      "sourceMap": true,
      "esModuleInterop": true,
      "allowJs": false,
      "allowSyntheticDefaultImports": true,
      "downlevelIteration": true,
      "noUnusedLocals": true,
      "noUnusedParameters": true,
      "noFallthroughCasesInSwitch": true,
      "forceConsistentCasingInFileNames": true,
      "strictNullChecks": true,
      "strictFunctionTypes": true,
      "strictBindCallApply": true,
      "strictPropertyInitialization": true,
      "baseUrl": "./src",
      "lib": [
        "dom",
        "es2016",
        "es2017.object"
      ],
      "outDir": "build"
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
      "node_modules",
      "**/*.spec.ts"
  ]
}
```

**Comment by rhlsthrm** [comment]
Ok this is weird, I can't reproduce it when I pull it out and start with the `combine`, but when the `combine` is part of a larger chain of `.andThen` that's where I'm getting issues. Is there any way you can take a look at my implementation @supermacro : https://github.com/connext/nxtp/blob/main/packages/router/src/handler.ts#L193?

I'd love to know if I'm doing something wrong, which is quite likely.

**Comment by supermacro** [comment]
There's a lot going on in that file 😅 I could try and reproduce the issue based on what you mentioned here: 

> but when the combine is part of a larger chain of .andThen that's where I'm getting issues

**Comment by supermacro** [comment]
@rhlsthrm did you ever figure out why this issue was occurring? If not, I think the best course of action might be to hop on a call and review the code together.

**Comment by supermacro** [comment]
Closing because of lack of response from @rhlsthrm, feel free to reopen though!
