### ISSUE TITLE
Pass data through `.andThen` chains

### ISSUE THREAD

**Issue by rhlsthrm** [supermacro/neverthrow#317]
I need some info on how to pass through data. For example:

```ts
resAsync.andThen(value => {
  const something = ...;
  return ResultAsync.fromPromise(
    someAsyncFn(...),
    (err) => new TypedError(...),
  );
}).andThen(valFromSomeAsyncFunction => {
  console.log(something.x); // error obviously
});
```

Is the best way simply to define outside of the chain, i.e. global? That seems "impure".

Another way is to change the fromPromise to something like:
```ts
ResultAsync.fromPromise(
  new Promise((res, rej) => {
    const valFromSomeAsyncFunction = someAsyncFn(...);
    res({ valFromSomeAsyncFunction, something });
  }),
  (err) => new TypedError(...),
);
```

This is a little ugly, but it works. Is there a better best practice? I'm trying to refactor my app to this library and still figuring out the best patterns.

**Comment by wibily** [comment]
The way to avoid defining things outside of the chain is to pass it in as an argument. Your second `andThen` function should be refactored to take in your `something` as an argument. I would suggest:
```
const someFn = something => valFromSomeAsyncFn => ...

const resultAsync = something => ResultAsync.fromPromise(
    someAsyncFn(...),
    (err) => new TypedError(...),
  ).andThen(someFn(something));


const finalResult = await somethingResultAsnyc(something);

```

**Comment by rhlsthrm** [comment]
Thanks, @wibily this is exactly what I needed!
