### ISSUE TITLE
Treating async operations as first-class citizens

### ISSUE THREAD

**Issue by paduc** [supermacro/neverthrow#32]
Hi and thanks for writing this cool library !
I've been looking at monad libraries for a while now and they all seamed unnecessarily complex to me. I came to the conclusion that the main (only?) benefit of Either types was to have typed Errors. When I read your blog article, I thought "right on !".

There is one thing that bugs me though and it has to do with handling async operations.
Your (great) library offers a ```Result``` type with a bunch of great api methods like map, mapErr, andThen, match, etc. but as soon as an operation is async, there aren't as many options.
I like the ```chain``` solution but it doesn't offer the same chainability as we would get with the synchronous ```Result```.

I understand this has to do with the fact that you don't have control over the api of ```Promise<Result>``` but I believe there might be an elegant solution: having a wrapper around that Promise. A ```ResultAsync<T>``` type that would have more or less the same api as ```Result<T>``` and could offer full chainability. 

Furthermore, I was thinking that whatever the ```Result``` could do, the ```ResultAsync``` could do too. Therefor, I'm not even sure we need both types, only the async version. In the Real World, there's always an async operation somewhere in the chain anyway, right ?

The method signatures would look something like this:
```typescript


map<U>(fn: T => U | T => Promise<U>):  ResultAsync<U, E>
mapErr<U>(fn: E => F | E => Promise<F>):  ResultAsync <T, F>
andThen<U>(fn: T => ResultAsync <U,E>): ResultAsync <U, E>
match<A>(
  okFn: (t:  T) =>  A,
  errFn: (e:  E) =>  A
): Promise<A>

then(cb: (T | E) => any) // a method to make the ResultAsync a thenable which can have the result extracted by calling either .then() or await

```

And a code example:
```typescript

const newUserId = await api.checkAvailability()
                           .andThen(api.createNewUser)
                           .map({ id } => id);

// newUserId is of type string | Error
if(newUserId instanceof Error){
   // newUserId is an Error
   console.log(newUserId.message);
}
else{
   // newUserId is a string
   console.log("new user id is ", newUserId)
}
```

Thanks again and looking forward to your thoughts !

**Comment by supermacro** [comment]
Hey @paduc,

Thanks for the kind words!

I like the idea, and this has been something that has crossed my mind in the past. So it's great to hear that others are thinking about it too.

I recently recalled that BlueBird implements its own Promise API that behaves much like native promises, except it adds a bunch more useful methods.

I'm not familiar with how BlueBird, or other libs, implement a `await`able object. If this is something that interests you, by all means I would support a PR that implements this.

**Comment by supermacro** [comment]
I do, however, I am not totally in agreement with your current API suggestion.

I think when you do: 

```typescript
await api.checkAvailability()
  .andThen(api.createNewUser)
  .map({ id } => id);
```

The resulting value should be a `Result` instance.

**Comment by paduc** [comment]
Great ! I'm glad you're open to the idea !

Regarding what you call making Result ```awaitable```, it's actually very easy. If an object or function defines a ```then()``` method, it is called ```thenable``` and can be used in conjunction with ```await``` or ```then``` ([see specification](https://promisesaplus.com)). I included it in my original post at the end of the method signatures.

As for the result of such an await, I thought you might prefer it returning a ```Result``` instance.
I'm dabbling with the idea that there could be no more ```Result``` at all (only ```ResultAsync```). In french, we have a saying "Qui peut le plus, peut le moins" which would translate to "He who can do the most, can do the least". If we have a ```ResultAsync``` capable of handling async and sync operations, we wouldn't really need ```Result``` which is only capable of handling sync operations. 

Do you have a use-case where you would want to wait for a ```ResultAsync``` to get a ```Result``` ? In my mind, I would only wait for a ```ResultAsync``` at the very top of my call stack, where I unpack the value or the error. I would see no need for the capabilities of the ```Result``` type.

I remain open-minded to having both ```Result``` and ```ResultAsync``` types of course, I'm just try to push the boundaries a bit.

I'm getting to work on a PR for the ```ResultAsync``` type.

**Comment by supermacro** [comment]
My apologies for missing your original `then` method!

I wasn't aware how simple it would be to make something awaitable. I haven't put in much thought around how things should work. But in a perfect world, `Result` would be enhanced to be `awaitable` without modifying the behaviour of the rest of the `Result` api (i.e. new features added without a breaking change).

Otherwise, I would like there to be a new `ResultAsync` function (in its own file - `result-async.ts` with accompanying tests) that duplicates the `Result` API. This is, again, very nice because it is not a breaking change for others.

**Comment by paduc** [comment]
No problem !

Making ```Result``` ```awaitable``` would indeed introduce a breaking change because ```await``` would be necessary to access the underlying value or error. 

I'm moving forward with a new ```ResultAsync``` (with it's own file and tests) that __mostly__ duplicates the ```Result``` API. I think ```Result.asyncMap``` would return a ```ResultAsync``` instead of the current ```Promise<Result<U,E>>``` so we could continue chaining.

**Comment by supermacro** [comment]
> I think Result.asyncMap would return a ResultAsync instead of the current Promise<Result<U,E>> so we could continue chaining.

Sounds good. As long as it's completely non-breaking!
