### ISSUE TITLE
Chaining issue...

### ISSUE THREAD

**Issue by tobydeh** [supermacro/neverthrow#326]
We have the following scenario:

```
const r = okAsync('ok1')
  .andThen(() => errAsync('err1'))
  .orElse(() => okAsync('ok2'));
```
r resolves to ok2, we need it to resolve to err1, essentially applying orElse() to the first result only.

match() solves the problem but the return type of Promise causes a big headache.

What is the best approach?

**Comment by supermacro** [comment]
Hey @tobydeh,

I'm not quite sure that I understand what you're telling me.

Would you be able to rephrase or give me another example? And what do you mean by " but the return type of Promise causes a big headache"? Are you trying to `await` something?

**Comment by tobydeh** [comment]
Here is an example that simplifies the problem, the return type of match() will not satisfy our ResultType<>.

```
type ResultType<T> = ResultAsync<T, ErrorType>;

public someMethod(): ResultType<number> {
  return okAsync(99)
    .match(
      res => okAsync(res),
      err => errAsync(err)
      )
}
```

**Comment by supermacro** [comment]
Ahhhh yes, now I understand. Yes, `match` on either a `Result` or `ResultAsync` will get rid of the corresponding `Result` / `ResultAsync`.

If you want to continue chaining on a `Result` then you should not use `match`. What you want is `map` and `mapErr` ... or if you're chaining with functions that themselves return a `Result` then you'll want to use `andThen`.


```typescript
type ResultType<T> = ResultAsync<T, ErrorType>;

public someMethod(): ResultType<number> {
  return okAsync('THIS IS NOT A NUMBER')
    .map((stringValue) => stringValue.length)
}
```

Does that make sense / answer your question?

**Comment by tobydeh** [comment]
Sorry, I'm not making myself clear.

Consider this contrived example... we execute a function that may or may not cause an error, we then handle the result using orElse / andThen to store some data. Both orElse & andThen return okAsync().

```
public callFunctionAndSaveTransaction (): ServiceResult<Transaction> {
    return mightEncouterError()
      .orElse(e => transactionRepo.save({ ..., error: true }))
      .andThen(e => transactionRepo.save({ ..., error: false }))
  }
```

In the above example andThen is called after orElse, because orElse returned okAsync(). Obviously we could place the andThen before the orElse however if the transactionRepo.save causes an error we would then trigger the orElse branch.

I hope that is a better example of the issue we're facing!

**Comment by paduc** [comment]
Hello @tobydeh,

I had a hard time figuring it out, but you might consider this solution:

```ts
public callFunctionAndSaveTransaction (): ServiceResult<Transaction> {
    return mightEncouterError()
      .map(res => ({ …res, error: false}))
      .orElse(e => okAsync({ ..., error: true }))
      .andThen(({ …res, error}) => transactionRepo.save({ res, error }))
  }
```

**Comment by tobydeh** [comment]
Thanks for your suggestion, I had considered something similar.

match() does what we want, but as mentioned above the return type causes problems.

Ultimately what we want is `mightEncounterError().similarToMatch(res => chain().on().good().branch(), error => chain().on().error().branch())`

**Comment by paduc** [comment]
Yeah what you want is a `flip` method that would transform an error into a result and vice versa. My suggestion let’s you do that by merging both cases in the « good branch » and « branding » your result as error/not-error within the object itself (ie adding a `result` property). You can than use `andThen` to split back into a error branch and a success branch.

```ts

public callFunctionAndSaveTransaction (): ServiceResult<Transaction> {
    return mightEncouterError()
      .map(res => ({ …res, error: false}))
      .orElse(e => okAsync({ ..., error: true }))
      .andThen(({ …res, error}) => error ? okAsync(…) : errAsync(…))
  }

```

**Comment by supermacro** [comment]
Because of lack of activity, I am closing this issue, but feel free to respond back here .. I can always reopen the issue.
