### ISSUE TITLE
Void return type

### ISSUE THREAD

**Issue by panwauu** [supermacro/neverthrow#363]
I want to use the Result type for a void function like this

```ts
import { Result, err, ok } from 'neverthrow';

function test(throwError: boolean): Result<void,string> {
  if (throwError) { return err('error') }
  return ok()
}
```

I got the problem that I dont know what to assign to ok. Typescript forces one argument. I cant use null because of strictNullCheck. 
I would prefer not returning at all, but if thats not possible it is no problem afterall.

**Comment by supermacro** [comment]
`void` represents the absence of a value.

Its usage is mainly for saying that a function doesn't explicitly return anything:

```typescript
const fn = (): void => {
  console.log('I dont explicitly return anything')
}
```

Note that the **value** returned from a `void` function is `undefined`. 

```typescript
const val = fn()

// val contains `undefined`
```

So based on these things, I would say what you probably want to specify in your `Result` is either `null` or `undefined`.

**Comment by panwauu** [comment]
Thanks for the clarification
