### ISSUE TITLE
Co-Dependent Async Calls

### ISSUE THREAD

**Issue by laurenzhonauer** [supermacro/neverthrow#376]
I love working with neverthrow so far. It forces me to be quite clean.

But sometimes when working in this functional way, I find myself writing code that is a bit harder to read than with an imperative style. I was wondering if there is something im doing wrong there, or if it is just a consequence of using the library properly.

``` 
Imperative
    const foo = await fooFn();
    if(foo === "not wanted") throw new Error("Not wanted");
 
    const bar = await barFn();
    if(bar=== "not wanted") throw new Error("Not wanted");

    const baz = await bazFn();
    if(baz === "not wanted") throw new Error("Not wanted");

    return "it worked";
```

```
Functional
    ResultAsync.fromPromise(fooFn(), () => "Error")
    .andThen(foo => {
        if(foo === "not wanted") return errAsync("Not wanted");
        return ResultAsync.fromPromise(barFn(), () => "Error")
        .andThen(bar => {
            if(bar=== "not wanted") return errAsync("Not wanted");
            return ResultAsync.fromPromise(bazFn(), () => "Error")
            .andThen(baz => {
                if(baz === "not wanted") return errAsync("Not wanted");
                return okAsync("It worked");
            }
        }
    }
```

Now imagine if fooFn and/or the others require multiple more params or if you have to extend the logic in any of the andThen blocks. It will become bloated very quickly.

I looked a bit into the [Example](https://github.com/parlez-vous/server). It would be awesome if you could point me to a function/file in there that handles my problem, or if it doesnt exist yet, explain to me how i can make the above look cleaner and me or someone else opens a pr in the example project :)

**Comment by supermacro** [comment]
Thanks for the kind words :)

Umm I mean the above example is a bit contrived, and this question really depends on the situation ... but in this specific example you don't need to nest. It's a matter of figuring out what's the type of your value that you're trying to have once your chain is completed / evaluated. The following works just the same:

From: https://replit.com/@gDelgado14/RequiredPuzzlingMarkuplanguage#index.ts

```typescript
const better = () =>
  ResultAsync.fromPromise(fooFn(), () => "Error")
    .andThen(foo => {
        if (foo === "not wanted") return errAsync("Not wanted");

        return ResultAsync.fromPromise(barFn(), () => "Error")
    })
    .andThen(bar => {
        if (bar === "not wanted") return errAsync("Not wanted");

        return ResultAsync.fromPromise(bazFn(), () => "Error")
    })
    .andThen(baz => {
        if (baz === "not wanted") return errAsync("Not wanted");

        return okAsync("It worked");
    })
```

At the end of this chain, you'd have a `ResultAsync<"it worked", "Error" | "Not Wanted">`

That being said, I'd encourage to ask yourself *why* you're needing to have so many if conditions in the first place ... or whether they are located in the right place.

**Comment by laurenzhonauer** [comment]
Oh, you opened my eyes a bit further there.

Thanks a lot for taking the time to provide the example! ❤️
