### ISSUE TITLE
Best practices for dealing with Promise based APIs?

### ISSUE THREAD

**Issue by evelant** [supermacro/neverthrow#378]
I'm having a bit of trouble finding an ergonomic pattern for dealing with a Promise based API. In particular I'm working with the google firestore API where I need to do transactions that follow this format:

```
let res: Promise<...> = firestore.runTransaction(async (transaction: Transaction) => {
    .... potentially a bunch of code needed in this fn
}
```

So I reach for the `fromPromise` API, but if I want to return a result from my transaction I end up with the following type

```
const res = ResultAsync.fromPromise(firesture.runTransction(async (transaction: Transaction) => {
     ....do some stuff
    return err("invalid data")
   .... do more stuff
   return ok(someData)
}, (err) => new FirestoreTransactionError(err))
```

 `ResultAsync<Err<unknown, string> | Ok<myDataType, unknown>, FirestoreTransactionError>`.   The best way I can see to unwrap the nested result is to chain a call to `andThen` with an identity function.

```
const res = ResultAsync.fromPromise(...firestore transaction)
                     .andThen(v => v)
                     .andThen((someData) => {
                            ....do stuff with result of successful transaction
                     })
```

It's not a big deal to unwrap it with that identity function but it feels like I must be missing a better way. Is there a better way to deal with APIs like this that insist on taking an async fn for an argument and returning a promise?

It gets even more difficult to deal with since the firestore transaction API requires you to call methods on the transaction API it passes to your async fn that return even more promises.

As a side note, would it be possible to infer `Result<T,U>` instead of `Err<unknown, U> | Ok<T, unknown>` without specifying T and U? Sometimes I have really really long types (mobx-state-tree) that are annoying to specify explicitly. I guess it doesn't really matter other than for easier to read types since I think those types are equivalent.

**Comment by evelant** [comment]
I suppose I can wrap that bit of boilerplate away like so

```
function transactionResult<T, U>(
    fn: (tran: Transaction) => Promise<Result<T, U>>
): ResultAsync<T, U | FirestoreTransactionFailedErr> {
    return ResultAsync.fromPromise(
        firestore.runTransaction(fn),
        (err: any) => new FirestoreTransactionFailedErr({ log, err })
    ).andThen((v) => v)
}

const test = transactionResult(async (trans) => {
        let bar = await trans.get(firestore.collection("foo").doc("bar"))
        if (!bar.exists) {
            return err("does not exist")
        } else {
            return ok(bar.data() as { foo: number })
        }
})
```

That's  a bit nicer to use. I guess I'd have to wrap all the functions on firestore's `transaction` if I wanted to really use it nicely with Result<>.

**Comment by Chuckytuh** [comment]
```
const res = ResultAsync.fromPromise(firesture.runTransction(async (transaction: Transaction) => {
     ....do some stuff
    return err("invalid data")
   .... do more stuff
   return ok(someData)
}, (err) => new FirestoreTransactionError(err))
```

By returning "err" you end up with that type signature, you should instead be rejecting the promise by either returning Promise.reject() or by throwing the err. That is then captured by the second function on the. `fromPromise` to transform the error to whatever type you want

**Comment by paduc** [comment]
I would limit the `neverthrow` types to outside the transaction.

Inside the callback passed to `runTransaction`, you could say that you are not in `neverthrow` territory, since `runTransaction` itself can throw. Therefor, I would not use `Err/Ok` inside the callback, but throw native errors, which are caught and handle with `fromPromise`.


```ts
const res: ResultAsync<string, Type1Error | Type2Error> = ResultAsync.fromPromise(firesture.runTransction(async (transaction: Transaction) => {
   // we are in async/await land
   if(something) throw new MyError()
   return "success"
}, (err) => {
  // we are mapping our async/await-land errors to neverthrow-land error type
  if(err instanceof MyError) return new Type1Error()
  return new Type2Error()
})
```

**Comment by evelant** [comment]
Here's what I ended up doing:

```
export function withTransaction<T, U>(
    fn: ({ trans }: { trans: Transaction }) => ResultAsync<T, U>
): ResultAsync<T, U | FirestoreTransactionFailedErr> {
    return ResultAsync.fromPromise(
        firestoreInstance.runTransaction(async (transaction) => {
            // transaction.getRes = transGet.bind(undefined, transaction)
            return fn({ trans: transaction })
        }),
        (err: any) => new FirestoreTransactionFailedErr({ log, err })
    ).andThen((v) => v)
}
```

Then I also made my functions take an optional transaction and return ResultAsync so I can use it like so:

```
const res: ResultAsync<void, 
                                       FirestoreTransactionError |
                                       FooError | 
                                      FirestoreNotFoundError | 
                                      FirestoreNotAuthorizedError> = withTransaction(({trans}) => 
     getDocById(some_id, "some_collection", trans).andThen(my_doc => {
            if(my_doc.foo) {
               return err(new FooError())
           } else {
               return saveDoc(my_doc, trans)
           }               
     })
    .andThen(.... and so on)
)
```

This way I can compose nice chains of Results and be able to handle the many possible error states. Before using never throw it was kinda impossible to figure out what errors might happen, it's great!

**Comment by supermacro** [comment]
Marking as closed since there hasn't been any activity in a while. Feel free to open a new issue any time!

**Comment by mikeburgh** [comment]
Just following up on this, I am looking for a pattern that calls async methods within a ResultAsync method..

The best I have come up with so far is as follows, however I feel the execute method gets a bit convoluted as it has to call connect first to ensure it's connected and using the andThen pattern (vs what would have been an await this.connect if the method was async execute(query:string): Promise<Result<DriverRecordSetItems,>> ) feels like it's starting to get messy.

Open to any other suggestions around how to structure something like this ?

```typescript
export class DB {

	private pool: any
	private connection:any //details omitted for brevity

	private connect(): ResultAsync<null, Error> {
		if (this.connection.connected) {
			return okAsync(null);
		}

		return ResultAsync.fromPromise(
			this.connection.connect(),
			(e: any) => e
		).andThen((pool) => {
			this.pool = pool;
			return okAsync(null);
		});
	}

	/* Execute a string of SQL! */
	execute(query: string): ResultAsync<RecordSetItems, Error> {
		
		return this.connect().andThen(() => {
			return ResultAsync.fromPromise(
				this.pool.query(query),
				(e: any) => e
			).andThen((results) => {
				return ok(
					results.recordsets.map((recordset: any) => {
						return {
							columns: recordset.columns,
							rows: recordset.map((row: any) => row),
						};
					})
				);
			});
		});

	}

	// Check our connection, so run empty query to check it works!
	check(): ResultAsync<null, Error> {
		return this.execute('SELECT 1').andThen((_) => ok(null));
	}
}
```

Calling check or execute on the class is ideal though as the error handling is consistent and much nicer than the try/catch or other patterns!

```typescript
const result = await instanceOfDb.check(); 
if (result.isErr()) {
....
}

```
