### ISSUE TITLE
Bug: overloaded combine API is unsafe

### ISSUE THREAD

**Issue by evelant** [supermacro/neverthrow#381]
The `combine` API was crashing on me in production, turns out there is a corner case due to typescript overloading

```typescript
const res: ResultAsync<void, void>[] = [errAsync(undefined)]
const res2: ResultAsync<void, void>[] = [okAsync(undefined)]
const combined = combine([combine(res), combine(res2)]).then((res) => {
    //no problem
})
```

```typescript
const res: ResultAsync<void, void>[] = []
const res2: ResultAsync<void, void>[] = [okAsync(undefined)]

//crash! TypeError: result.isErr is not a function
const combined = combine([combine(res), combine(res2)]).then((res) => {
   
})
```

The overload here is the issue https://github.com/supermacro/neverthrow/blob/524a15a100034f2d74a2a39e1fb1ed5937da41a2/src/utils.ts#L65-L71

If you ever pass an empty array to `combine` you get unexpected behavior since it _always_ returns a `Result` in that case even if the type should be a `ResultAsync` which results in a crash in some cases.

Unfortunately I don't see any way to resolve this other than separating `combine` into `combine` and `combineAsync`. Thoughts?

**Comment by supermacro** [comment]
Hey, good find! I'm surprised this issue hasn't come up sooner.

> Unfortunately I don't see any way to resolve this other than separating combine into combine and combineAsync. Thoughts?

Hmm, why couldn't we do something like this:

```typescript
export function combineWithAllErrors(list: any): any {
  if (list.length === 0) return []

  if (list[0] instanceof ResultAsync) {
    return combineResultAsyncListWithAllErrors(list)
  } else {
    return combineResultListWithAllErrors(list)
  }
}
```

Intuitively this seems to be a good solution to me, but maybe I'm missing something?

**Comment by supermacro** [comment]
Wait what am I saying my solution doesn't even compile 🤣 

Yeah I get what you're saying now. There's no way to know if we should return a `ResultAsync` or a `Result` when there's an empty list.

I think another solution in contrast to what you proposed is to define a type that is not `Result<unknown, unknown>[]` or `T extends readonly ResultAsync<unknown, unknown>[]`

We'd want something that is seen as different than the array type `[]`

Perhaps non-empty array?

```
type NonEmptyArray<T> = [ T, ...T[] ]
```

Here's an example that intentionally does not compile:

```typescript

type NonEmptyArray<T> = [ T, ...T[] ]

const maybeEmpty: string[] = []

const definitelyNotEmpty: NonEmptyArray<string> = b  // error
```

**Comment by evelant** [comment]
Since the API is already separated by async/non-async in most places I think it would make sense, be consistent, and be simplest to just split it into combine/combineAsync. It would be nice if TS easily supported these sorts of APIs but all the gymnastics done for the sake of (IMO) dogmatic adherence to structural typing and JS quirks makes it tough. Until everyone can be convinced to use a compile-to-js language with a better type system like [rescript](https://rescript-lang.org) 😊 I think it's best to keep combine simpler and consistent with the other APIs by splitting it up

**Comment by supermacro** [comment]
Need to think about this

**Comment by supermacro** [comment]
I agree with your recommendation @evelant ... going to create separate APIs:

**For `Result`**

- `combine`
- `combineWithAllErrors`


**For `ResultAsync`**

- `combineAsync`
- `combineWithAllErrorsAsync`

This will unfortunately require a release under a new MAJOR version.

**Comment by supermacro** [comment]
Not sure when I'll get around to this tbh 🤷 but always happy to accept contributions!
