### ISSUE TITLE
Question: How to propagate errors with eslint plugin

### ISSUE THREAD

**Issue by on3iro** [supermacro/neverthrow#385]
Hey folks,

I just discovered this library. I also immediately installed the eslint-plugin.
However one thing I can't wrap my head around is, how errors could be propagated up the call stack with the eslint-plugin enabled.

Lets say i have an inner function called by an outer function.
Both should be able to return a `Result<undefined, Error>`.
Now when my inner function returns an Err() result I need to either use `match` or `unwrapOr`.
However what I would actually like to do, is to check `result.isErr()` inside my outer function and return the error if it is one and otherwise proceed with function execution.

What am I missing here?

Thanks in advance :)

**Comment by supermacro** [comment]
It's probably because I am just waking up, but I can't wrap my head around your hypothetical example at the moment. Could you actually write a code snippet that reproduces the issue you're having?

**Comment by supermacro** [comment]
And you're saying that you're getting lint errors from `eslint-plugin-neverthrow` because you're not calling `.match` or `unwrapOr` on the `innerResult` value?

**Comment by on3iro** [comment]
@supermacro exactly.

here's my eslint config:

```json
 "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest",
      "plugin:neverthrow/recommended"
    ],
    "plugins": [
      "neverthrow"
    ],
    "rules": {
      "neverthrow/must-use-result": "error"
    },
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
      "ecmaVersion": 2021,
      "sourceType": "module",
      "project": [
        "./tsconfig.json"
      ]
    }
  },
```

**Comment by supermacro** [comment]
Ok. It does make sense that `eslint-plugin-neverthrow`would raise an error here.

What you'd want to do is to refactor the code such that you don't have an intermediary variable containing a result (currently that is what `innerResult` is).

Hence you'd end up with:

```typescript
const outerFn = (): Result<undefined, string> => {

 return innerFn()
  .map((val) =>
     // ...do something
    something(val)
  )
  // this next line is optional if you 
  .mapErr((error) =>
    handleError(error)
  )
}
```

**Comment by on3iro** [comment]
Ah interesting. Thanks for the example. How would I handle a list of `Result`-values then?
For example:

```ts
  const resultListWithPossibleErrors = flattenedTargets
    .filter((t) => t.isValid)
    .map((t) => dealDamage(G, t, targetPlayerID))
```

**Comment by supermacro** [comment]
Depends on how you want to do things. 

There's two utilities called `combine` and `combineWithAllErrors`.

```typescript
const list1 = [
  ok(123),
  err('boom'),
  ok(456),
  err('woof'),
]

// outcome1 is err('boom')
// it short-circuits on first error
const outcome1 = combine(list1)

// outcome1 is err([ 'boom', 'woof' ])
// it iterates through whole list and aggregates all errors 
const outcome2 = combineWithAllErrors(list1) 
```


In either case `outcome1` and `outcome2` are also `Result`s ... so you can also `.map` those or use the whole `neverthrow` api just like before

**Comment by on3iro** [comment]
Awesome, thanks for the quick answers. <3
