### ISSUE TITLE
Opinion/Feedback/Question Best Practices on using neverthrow

### ISSUE THREAD

**Issue by provdlaw** [supermacro/neverthrow#397]
Hi,

Let's say I have recently inherited a code project which uses neverthrow for error handling. To me, the advantages of neverthrow over throwing an error is not fully apparent. 

Firstly, when writing a function that returns a Result<any, err>, the **entirety of the function body has to be in a try-catch block**. If this rule is not followed, then the neverthrow paradigm is broken
```
function b(): Result<any, Error> {
  a(); // if a throws, then b() will throw. Therefore, all code should be in a try-catch
  try { 
      ...
  } catch(error) {
     err(error);
  }
}
```

Generally, I find that developers will eventually write function that potentially throws, and we overcompensate this by having both a try-catch on top of checking the result value.
```
try {
    const exampleReceived = await this.getExample("something");
    if (exampleReceived.isErr()) {
        return err(exampleReceived.error)
    }
    const example = exampleReceived.value;
    //business logic
} catch (error) {
    return err(error);
}
```

How do you suggest we avoid having to do the above?

**Comment by supermacro** [comment]
hey @provdlaw,

While transitioning from a codebase that uses `throw` frequently to one that uses `throw` sparingly means that you do have to wrap certain functions in `try / catch` blocks.

But this shouldn't be done on the ideological basis that "anything can throw". Technically-speaking, yes, you're right. Who knows whether `Boolean(123)` will one day decide to throw an exception. But that's overly defensive programming.

So my recommendation is to only wrap in a `try/catch` what you know is designed to throw under certain circumstances. The issue of "I find that developers will eventually write function that potentially throws", is more of a cultural one for your team. Your team has to have a discussion regarding coding conventions and agree to not use `throw` excessively when returning a simple value (not even a `Result`) would have been sufficient. 

So my recommendation is:

- Have a discussion with the team regarding whether folks even like this functional & declarative approach to error management ... maybe the simple solution is `npm uninstall neverthrow`
- If they do, then a discussion needs to be had around when it is appropriate to use `throw` and when it is
- Then avoid using `try / catch` out of fear that a teammate may have snuck a `throw` statement in there in spite of the coding conventions

**Comment by supermacro** [comment]
Closing this issue, but let me know if you have any other questions or anything!
