### ISSUE TITLE
fromSafePromise error type must be "never"

### ISSUE THREAD

**Issue by lmcsu** [supermacro/neverthrow#407]
```
const r = ResultAsync
    .fromSafePromise(new Promise<number>((resolve) => resolve(123)))
    .andThen((num) => {
        return errAsync(num);
    });
```
its type is `ResultAsync<never, unknown>` instead of `ResultAsync<never, number>`
because fromSafePromise returns `ResultAsync<type, unknown>` and "unknown" is kinda heavier than anything else I guess.
so everywhere we must write it as `fromSafePromise<type, never>` to make it work

**Comment by supermacro** [comment]
Hey, sorry for the incredibly late response here. But yes, I do agree - and I am open to the suggestion posted by @msheakoski .. will gladly review if the PR is open.

**Comment by ccjmne** [comment]
I'd be open to looking into it, but I think I'd probably end up merely committing @msheakoski's solution.
If they aren't too active anymore, maybe a co-authored commit would be suitable?

**Comment by lmcsu** [comment]
@ccjmne just make it.
Somebody has to make it finally.
Doesn't matter who.
I'm kinda bad at git workflows, so I prefer to just watch and wait.
