### ISSUE TITLE
Promise<Result<>> vs. ResultAsync<>

### ISSUE THREAD

**Issue by drmikecrowe** [supermacro/neverthrow#42]
This may be obvious, but I thought I could do the following:

```ts
async function pfun(): ResultAsync<str, Error> {
    return okAsync("Yes");
}
```

as opposed to:

```ts
async function pfun(): Promise<Result<<str, Error>> {
    return ok("Yes");
}
```

Is that not the purpose of `ResultAsync`?

When I try the former, I get:
```
The return type of an async function or method must be the global Promise<T> type.
```

**Comment by supermacro** [comment]
Hey @drmikecrowe,

Great question. So although `ResultAsync` is "thenable" as per the [promise A+ specification](https://promisesaplus.com), and as such behaves just like a promise ... it is not what gets returned when you use an `async` function.

JavaScript (and, by implication, TypeScript) automatically wraps your return value inside of a `Promise` whenever you use `async`. 

Thus the function `const ex = async () => 123` returns a `Promise<number>`. 

The implication being that if you use `async` syntax, you cannot return a `ResultAsync`.

Does that make sense? Let me know if you have a use case where this restriction is cumbersome / limiting.

**Comment by drmikecrowe** [comment]
Yes, that helps, thanks.

**Comment by alexkreidler** [comment]
I'm finding myself in a situation where I'm having to revert back to using a bunch of lower level Promise syntax instead of async/await which I find much more idiomatic.

In most typescript projects, async/await gets compiled down to regular Promises or a polyfill for Generators

Is is possible to create a result type that works within the async/await syntax?

**Comment by paduc** [comment]
@alexkreidler could you give an example of where the current syntax doesn’t quite fit ?

You can already use the async/await syntax with ResultAsync. When you await a ResultAsync, it produces a Result.
