### ISSUE TITLE
Enormous declaration files that hang everything since 5.1.0

### ISSUE THREAD

**Issue by lmcsu** [supermacro/neverthrow#433]
I want to re-export the combine functions like this
```typescript
import { Result } from 'neverthrow';
export function combine<T extends Result<unknown, unknown>[]>(resultList: T) {
    return Result.combine(resultList);
}
```

It works fine, but the d.ts file becomes so huge that it entirely hangs the IDE and the typescript compiler, so it's impossible to use that declaration file in any other project.

I don't know why that happens, maybe it's a tsc issue or something else, but it was working fine before version 5.1.0.

![image](https://user-images.githubusercontent.com/34189985/200291928-a2102d66-7e4c-4309-9bdf-1cc63b1fafce.png)

**Comment by supermacro** [comment]
This is due to the recursive nature of the generic types inside of this project since https://github.com/supermacro/neverthrow/releases/tag/v5.1.0

@lmcsu Are you still facing this issue / did you find a workaround?

**Comment by lmcsu** [comment]
@supermacro still facing, found no workaround, still using 5.0.1 ☹️

**Comment by m-shaka** [comment]
If you just want to re-export `combine`, it works

```typescript
import { Result } from 'neverthrow';

export const combine = Result.combine;

// d.ts
import { Result } from 'neverthrow';
export declare const combine: typeof Result.combine;
```

**Comment by supermacro** [comment]
Marking as closed assuming @m-shaka's suggestion fixes this issue
