### ISSUE TITLE
Result.combine is broken for array types that are not tuple types

### ISSUE THREAD

**Issue by ghost91-** [supermacro/neverthrow#434]
Since https://github.com/supermacro/neverthrow/issues/226 has been merged, `Result.combine` is broken for array types that are not tuple types:

```ts
import { Result } from "neverthrow";

const results: Result<string, string>[] = [];
const result = Result.combine(results); // inferred as Result<unknown, never>, but should be Result<string[], string>
```

Earlier, I had thought that this was actually related to the TypeScript option `strictFunctionTypes`, but it turns out, this is broken even with that option disabled.

Regardless, I see that neverthrow itself currently does not enable `strict` or `strictFunctionTypes` in its `tsconfig.json`, which is probably how this slipped through. I think in this day and age, enabling `strict` should be the default to ensure proper type safety, so I would recommend that neverthrow start using it, too :)

**Comment by ghost91-** [comment]
So, I have dug into this a little bit, and it seems there are multiple issues.

1. `MemberListOf` seems to be an incorrect implementation of a `UnionToTuple` type, as described for example in https://stackoverflow.com/a/55128956. The comment above `MemberListOf` says
   ```ts
   Given a union, this gives the array of the union members.
   ```
   While that description is a bit unclear (and I think it deserves a documentation comment of a regular one), I guess this means it _should_ act like a `UnionToTuple` type. But at the moment, it just returns `[]` regardless of what union type you pass in.
2. Even if we replace the implementation of `MemberListOf` with a correct one (e.g., the one from the stackoverflow post above), it's still broken. That is because `CombineResults` then puts this into `Traverse`, and it is being handled basically just like the tuple case, which means, the result becomes a tuple (of length of the number different types in the ok cases of the original result array). I believe that instead of handling these cases (tuples and arrays) in the same way, we need to make a differentiation here. The case for arrays should be a lot simpler anyways..

Unfortunately, I don't really have the time to go all the way and implement a fix for this. Too much knowledge about these internal types (`Traverse`, `Transpose`, `CollectResults`, etc.), and how they work together, is needed. Maybe you could take a look, @incetarik, since you have originally implemented this?

**Comment by ghost91-** [comment]
Also note that this is blocking us from upgrading neverthrow. We have currently pinned the version of neverthrow to `~5.0.0`, because this issue breaks a whole lot of our code.. In particular, we would not be able to upgrade in case of a security fix :/

**Comment by incetarik** [comment]
@ghost91- Unfortunately I'm pretty busy too. If you did go through those types and saw things, you may also consider having a list of the things should be done as well and maybe writing a test for them? Because although I'm aware of the issue of unions to tuple with typescipt, this was the way to provide the required information. Maybe this will end up with changing the base types and we will not have union types when representing a Result.

**Comment by ghost91-** [comment]
@incetarik

>  this was the way to provide the required information
Not exactly sure what you mean, but the way it is now, it just straight up does not work. It _does_ work correctly for tuples of `Result`s, but is completely broken for arrays of `Result`s. Unfortunately, at the moment, there is actually no test case for the array case, which is probably how this slipped through. But the test case is actually very simple:
```ts
    (function it(_ = 'combines arrays of results to a result of an array') {
      type Expectation = Result<string[], string>;
      const results: Result<string, string>[] = []

      const result: Expectation = Result.combine(results); // fails right now :(
    });
```

@supermacro Any suggestions on how to proceed here?

**Comment by incetarik** [comment]
If I have free time, I think I can fix it pretty easily but I cannot promise. Until then I think the best would be using the previous version instead. As you referred one of the types as incorrectly implemented, therefore you have seen something incorrect, until the time I can come back to this, you can try fixing it or providing a solution to the problem that is marked as solved with that merge, with your own solution.
