### ISSUE TITLE
`Result.combine` inferred incorrectly when input is nested array

### ISSUE THREAD

**Issue by h-yon** [supermacro/neverthrow#441]
`Result.combine` is not correctly inferred in the following code with v6.0.0.

```ts
import { ok, Result } from 'neverthrow'

const tuple = <T extends unknown[]>(...args: T): T => args

const string = ok('string')
const number = ok(1)

const numbers1 = Result.combine([...Array(1).keys()].map(ok))
const numbers2 = Result.combine([...Array(2).keys()].map(ok))
const numbers3 = Result.combine([...Array(3).keys()].map(ok))
const numbers4 = Result.combine([...Array(4).keys()].map(ok))

// ↓ should be Result<[string, number, number[], number[], number[], number[]], never> but inferred as Result<never, never>
const values = Result.combine(tuple(string, number, numbers1, numbers2, numbers3, numbers4))
```

I made sample repo to reproduce: https://github.com/h-yon/nt-test

Curiously, this problem does not occur when [downgrading to v5.0.1](https://github.com/h-yon/nt-test/pull/1) or [reducing variable](https://github.com/h-yon/nt-test/pull/2)

**Comment by brndt** [comment]
Yes, also if you have more than five elements in array it infers type as Result<never, never>:
`const test = Result.combine([ok(1), ok(1), ok(1), ok(1), ok(1), ok(1)])
// const test: Result<never, never>`

**Comment by supermacro** [comment]
The issue is that currently there's a recursion depth limit of `5` iterations. See https://github.com/supermacro/neverthrow/pull/468, where I increase the iteration count to 50 - meaning now `neverthrow` would be able to have inference of tuples containing up to 50 elements.

**Comment by supermacro** [comment]
https://github.com/supermacro/neverthrow/releases/tag/v6.0.1-0
