### ISSUE TITLE
Wiki Contribution

### ISSUE THREAD

**Issue by lauhon** [supermacro/neverthrow#452]
Hey,

I'm planning to make a talk about neverthrow in a local community meetup (in vienna). I wanted to force myself to understand the usage of the package properly and noticed some wiki pages that seemed to need some love.

Therefore I created a fork and added some docs there.
https://github.com/lauhon/neverthrow-wiki-fork/pull/1

I am planning to write about working with result async and how to incorporate side effects

Would be nice to get your feedback on this and hopefully incorporate what I wrote into the actual wiki :)

**Comment by lauhon** [comment]
Btw: I created the fork because I did not see a way for me to contribute to the wiki in the original project. 
Please let me know if this is the right way to contribute to the wiki

**Comment by supermacro** [comment]
That's great! Thank you for this. The biggest hurdle to embracing this sort of paradigm for error handling is providing lots of documentation and examples! Really appreciate it. 

And yes, I am more than happy to incorporate this into the wiki here - I posted some comments on your PR.

**Comment by supermacro** [comment]
The contribution has since been added.

Context: https://github.com/lauhon/neverthrow-wiki-fork/pull/1#issuecomment-1469867573
