### ISSUE TITLE
fromPromise always prints warning

### ISSUE THREAD

**Issue by jsmith** [supermacro/neverthrow#46]
It seems like the logic in `fromPromise` prints:
```
[neverthrow] - `fromPromise` called without a promise rejection handler - Ensure that you are catching promise rejections yourself, or pass a second argument to `fromPromsie` to convert a caught exception into an `Err` instance
```

when the `errorFn` *is* defined. This logic is backwards, right?

See https://github.com/supermacro/neverthrow/blob/master/src/result-async.ts#L27
Also see my commit that fixes it: https://github.com/supermacro/neverthrow/commit/6294b2c6f19fe60126c26848c795008aab5af67a

Do you want me to create the PR? I know that travis is broken for contributors but I could test locally if you want?

**Comment by supermacro** [comment]
Hey @jsmith,

Ahh, yes good catch.

Contributions are welcome. Yes, please run CI checks locally. I will also run them on my machine before any merging is done.

For context, the intended logic in the if block that you reference was:

```
If (is_browser_environment OR
   (is_node_environment AND NODE_ENV !== production)) AND
   errorFn_not_defined
then
  log warning to user
```
