### ISSUE TITLE
I want pass an async function to Result.mapErr().

### ISSUE THREAD

**Issue by mitsuru793** [supermacro/neverthrow#491]
Thank you for maintaining this library.

I have a question to how to writing code.
I want to call an async function after a sync function.
I want to use 'await' to the async function.
How should I write code?

I have read issues and wiki, but I haven't know it. Sorry.

# Env
- node v20.6.0
- TypeScript 5.2.2
- neverthrow 6.0.0

# Source
- I will find cache by sync. If not found, I will call the async api function.

```ts
import { Result, err, ok } from 'neverthrow'

import * as fs from 'fs'

const readCache = (cacheFilePath: string): Result<string, Error> => {
    if (fs.existsSync(cacheFilePath)) {
        console.log('found cache')
        const cacheContent = fs.readFileSync(cacheFilePath).toString()
        return ok(cacheContent)
    }
    console.log('not found cache')
    return err(new Error(`Not found cache: ${cacheFilePath}`))
}

const requestByApi = async (): Promise<string> => {
    console.log('calling api...')
    return Promise.resolve('new content')
}

readCache('/cache/f1.json')
    .mapErr(async (_: Error) => await requestByApi())
    .map((content: string) => {
        console.log(`got ${content}`)
    })
console.log('finish')
```

The following is output of result.

```text
not found cache
calling api...
finish
```

However, I want other output of the following.

```text
not found cache
calling api...
got new content
finish
```

**Comment by mitsuru793** [comment]
I know how to use `fromPromise` and rewrite code, but I got compile error from TypeScript.

```ts
const requestByApi = async (): Promise<string> => {
    console.log('calling api...')
    return Promise.resolve('new content')
}

// Argument of type '() => Promise<string>' is not assignable to parameter of type 'PromiseLike<unknown>'.
const safeRequestByApi = ResultAsync.fromPromise(requestByApi, (e) => e)
```

**Comment by paduc** [comment]
Hello @mitsuru793 

I’m sorry I can’t write a full response as I am away but you should replace your mapErr with orElse (see doc). 

To fix the error above you need to pass a promise to fromPromise. Here you pass a function that returns a promise.

**Comment by mitsuru793** [comment]
@paduc 
Thank you very much.

`orElse` is useful, but it cannot use `await` inside it.
Can't neverthrow chain sync and async function?

```ts
const safeRequestByApi = Result.fromThrowable(requestByApi, (e) => e)

readCache('/cache/f1.json')
    .orElse((_: Error) => safeRequestByApi())
    .map((content: string) => {
        console.log(`got ${content}`)
    })
console.log('finish')
```

got output
```
not found cache
calling api...
got [object Promise]
finish
```

I expected output.
```
not found cache
calling api...
got new content
finish
```

I want to write the following.
```ts
readCache('/cache/f1.json')
    .orElse(async (_: Error) => await safeRequestByApi())
    .map((content: string) => {
        console.log(`got ${content}`)
    })
```

---

I have understand the error of `fromPromise`. Thank you.
However, this take the result of function.

```ts
// run requestByApi here. I want not to run here.
const safeRequestByApi = ResultAsync.fromPromise(requestByApi(), (e) => e)
```

**Comment by paduc** [comment]
@mitsuru793 

> @paduc Thank you very much.
> 
> `orElse` is useful, but it cannot use `await` inside it. Can't neverthrow chain sync and async function?
> 

Yes it can. When you start with a sync `Result` and you want to chain with something that returns a `ResultAsync`, you need to use async variants (see `Result.asyncMap`). I see that there is no async variant for `orElse` (a PR would be welcome).

If you start with a `ResultAsync` you won't have this problem.

```ts
 okAsync() // only to start with an async object
     .andThen(() => readCache('/cache/f1.json'))
     .orElse((_: Error) => safeRequestByApi())
     .map((content: string) => {
         console.log(`got ${content}`)
     })
```

> I want to write the following.
> 
> ```ts
> readCache('/cache/f1.json')
>     .orElse(async (_: Error) => await safeRequestByApi())
>     .map((content: string) => {
>         console.log(`got ${content}`)
>     })
> ```
> 

`orElse` only takes functions that return a `Result/ResultAsync`, not a promise. Therefor, you cannot use `await`. It's fundamental to `neverthrow`. 

> I have understand the error of `fromPromise`. Thank you. However, this take the result of function.
> 
> ```ts
> // run requestByApi here. I want not to run here.
> const safeRequestByApi = ResultAsync.fromPromise(requestByApi(), (e) => e)
> ```

You can use a function:

```ts

const safeRequestByApi  = (params) => {
   return ResultAsync.fromPromise(requestByApi(params), (e) => e)
}

```

**Comment by mitsuru793** [comment]
@paduc 
Thank you very much and your answer is amazing!
I have resolved my issue by you.
I will close with my issue.
