### ISSUE TITLE
Returning from a much-needed break

### ISSUE THREAD

**Issue by supermacro** [supermacro/neverthrow#496]
Hey everyone ... I want to apologize for disappearing here on the `neverthrow` repo for a few months. I did not have the time to focus on this project - but now I am in a much better place to be able to come back and provide proper care and maintenance to neverthrow.

In the coming days & weeks I will begin going through issues and PRs.

###  Open PRs

For the currently-open PRS, I will refresh my memory on them. If I agree with the PR then I will see if it is already in a mergeable state. If so I will merge.

If the PR is not in a mergeable state, I will contact the original author and see if they are open to getting the PR in a mergeable state. If not, then I may dedicate time to taking over the PR and getting it merged - but this is not a guarantee.

If I disagree with the PR then I will comment on the PR mentioning my counterpoints and await a response - if I do not hear back after a while then I will likely close the PR.

---- 

Thank you for your patience & understanding :heart:

**Comment by inaiat** [comment]
This is awesome! Great to hear that. Sometimes we need a break, its good. If you need some help to test and keep project up to date, don't hesitate to contact me. 

Thank you for give us a great library.
