### ISSUE TITLE
Seeking maintainer

### ISSUE THREAD

**Issue by supermacro** [supermacro/neverthrow#531]
Hey everyone! Sorry for going MIA ... I'm starting a new company and unfortunately haven't had the time to give neverthrow the love it deserves.

If you'd be interested in being a maintainer for neverthrow please shoot me an email at opensource [at] gdelgado.ca

More than anything I'm looking for someone who is:

A) passionate about neverthrow
B) has deep typescript expertise

Looking forward to chatting with you!

**Comment by 0xksure** [comment]
Hi! An alternative would be using something like sandblizzard.one to allow people to create bounties attached to issues. This would encourage new contributors while at the same time let the project continue to develop.

**Comment by supermacro** [comment]
# :eyes: UPDATE

I'm happy to share that @m-shaka has been helping me out for the last month or so on bringing `neverthrow`'s development back.

We are in the early days of working together, so it wil ltake a bit of time before we establish a good rhytm, but there have already been some great contributions provided by @m-shaka. 

Our hope is that in the coming weeks and months we'll bring down the open PR count down to 0 and also groom outstanding issues.

**Comment by dmmulroy** [comment]
@supermacro and @m-shaka I'm a engineer at vercel who uses `neverthrow` heavily. I have experience maintaining typescript oss such as https://github.com/FormidableLabs/victory, https://github/dmmulroy/tsc.nvim, etc.

If y'all are looking for more help I'd be more than happy to jump in and or even chat.

**Comment by jdes01** [comment]
Hey! im not the most senior dev ever, but trully love this library, feel free to tag me if you guys think I can help 😼

**Comment by supermacro** [comment]
Hey @dmmulroy & @jdes01 thank you for the support. At the moment I think that @m-shaka and I are ok, but I have been thinking of perhaps creating a neverthrow discord server that could have a channel(s) for contributors / maintainers ... just an idea atm.

**Comment by japhethkiptoo** [comment]
Hi @supermacro, this is a great solution.
I am a Rust and Typescript engineer 
and passionate about error handling.
I am the author of https://www.npmjs.com/package/js-exceptions
If you ever need help kindly reach-out.
Thanks

**Comment by macksal** [comment]
Hi @supermacro I am able to help maintaining the library if needed. Writing TS since 2019ish.  Using neverthrow in a production app with 7500 monthly users. I recently contributed #588 and #584.
