### ISSUE TITLE
Publish ESM Version

### ISSUE THREAD

**Issue by jsmith** [supermacro/neverthrow#58]
I think it would be beneficial to publish a ES module version alongside the commonjs version using the `module` field in the `package.json`. I've done this once with another package I made and I used `rollup` to build both versions. If you think this is a good idea, I could make a PR?

**Comment by supermacro** [comment]
Hey @jsmith, I'm intrigued.

However, I'm not very informed on the potential drawbacks and associated benefits of having two separate module types. 

### Questions:

- Is this a breaking change?
- what are the tangible benefits
- anything else that I or users should be aware of?

**Comment by jsmith** [comment]
No potential drawbacks from my understanding :) ES2015 JavaScript modules are the new standard and the `module` field is a way for libraries to support both commonjs and the new ES module standard with no breaking changes (ie. the user needs to be aware of nothing). Other than supporting the current standard (ie. a supported by node v14 *and* modern web browsers) one of the best tangible benefits is better tree-shaking support. To give an example of the power of tree shaking, I'm currently working on a web project that is ~ 8MB when built without tree shaking and ~ 800 KB when built with tree shaking.

For context on why I created this issue, I was trying to use `ResultAsync` in a [`vite`](https://github.com/vitejs/vite) dev build but was encountering an issue (`Result` still worked for some reason). Vite, an ES Module based web dev tool , uses the [`commonjs`](https://github.com/rollup/plugins/tree/master/packages/commonjs) rollup plugin to convert commonjs -> ES Modules but incorrectly converted the `result-async.js` file for some reason :( I don't understand enough about how the plugin does the conversion but publishing an ES Module version of `neverthrow` would fix this!

If I have time this weekend, I'll make this change on a branch and create a PR :)
