### ISSUE TITLE
Unable to build (and publish) ESM version of package

### ISSUE THREAD

**Issue by supermacro** [supermacro/neverthrow#63]
cc @jsmith 

I was going to publish the latest version of `neverthrow` to npm via a `beta` flag to sanity check for any breaking changes and was unable to build out the package.

See the following screenshot:

<img width="1440" alt="Screen Shot 2020-06-18 at 8 40 38 AM" src="https://user-images.githubusercontent.com/10621548/85021258-9d663a80-b13f-11ea-9ed0-92dde27ac33f.png">

Any ideas on how to fix this?

**Comment by jsmith** [comment]
Let me check, sorry!! I never had any issues with this, maybe it's an OS thing? Anyway, I'll get back to you later today :)

**Comment by supermacro** [comment]
FYI: I ran the above on a MacBook Pro on macOS Catalina v10.15.5. 

I also have a ubuntu-based linux machine that I'm also going to run some tests on before officially publishing this new version under the `latest` tag on npm.

**Comment by jsmith** [comment]
Oops for some reason I though the screenshot was taken on Windows. Anyway, I think I fixed it :)

**Comment by supermacro** [comment]
@jsmith published behind a `beta` flag: `npm install neverthrow@beta`. 

Would appreciate feedback on how it's behaving with this new build setup.

**Comment by jsmith** [comment]
Yay, I'll test the new build later today! Thanks for publishing :)

**Comment by jsmith** [comment]
Ok I tested `index.cjs.js` using a simple node script and using jest. In addition, I tested `index.es.js` using [`vite`](https://github.com/vitejs/vite). Everything seems to be working as expected :) I didn't test *everything* but I can confirm that `neverthrow` can be imported as expected and that the subset of functionality I tested worked normally.
