### ISSUE TITLE
problem in a rollup project

### ISSUE THREAD

**Issue by bastianh** [supermacro/neverthrow#69]
Hi,
I'm currently using the 2.2 version of the library in a small project... I tried to upgrade the library today and have a problem that it won't work anymore.
The error I get is:
```
(!) Circular dependencies
node_modules/neverthrow/dist/index.js -> node_modules/neverthrow/dist/result.js -> node_modules/neverthrow/dist/index.js
node_modules/neverthrow/dist/index.js -> node_modules/neverthrow/dist/result.js -> /Users/bho/Development/adventureland/node_modules/neverthrow/dist/index.js?commonjs-proxy -> node_modules/neverthrow/dist/index.js
node_modules/neverthrow/dist/index.js -> node_modules/neverthrow/dist/result-async.js -> node_modules/neverthrow/dist/index.js
[!] Error: 'ok' is not exported by node_modules/neverthrow/dist/index.js, imported by src/utils/move.ts
```
probably it's me doing something wrong.. can you help me?

edit: after upgrading all rollup plugins it compiles again, but those messages remained as warnings.

**Comment by supermacro** [comment]
Hey @bastianh,

Let me take a look.

Going to cc @jsmith here because he knows more about rollup than I do.

**Comment by jsmith** [comment]
I think this might be an issue with `2.4.0`? If we publish `2.5.0` then this should go away since rollup actually takes `index.js` and `result.js` and creates a single js file as output so there shouldn't be any circular dependencies. This commit https://github.com/supermacro/neverthrow/commit/e6c2e6962478eaa11bd1e93fff2fbc24ef3f0b51#diff-13618125a1b532b291c07ad8ac3dc6b8 added an import from `index.ts` which did cause a circular import but it seems like most build systems can handle this!

**Comment by supermacro** [comment]
So looking through the [releases](https://github.com/supermacro/neverthrow/releases) page, I can see that the package back then didn't have any fancy build steps. 

Secondly, I checked out the `v2.2.0` code and built it, and did not find a circular dependency as illustrated on your comment. 

`v2.2.0` is the only `v2.2.x` version of this package. 

Secondly, in your logs I see output that references `result-async.js`, which suggests to me that your neverthrow version is **at least** `v2.3.0`.

So I went ahead and checked out the source at `v2.3.2` to see if there were any strange circular dependencies. **I found circular dependencies in this release**.

But as @jsmith mentioned, the latest version no longer has this problem.

The solution is to upgrade `neverthrow` to `v2.5`. Right now it's sitting behind a beta flag, but it looks like it's working fine, so I will publish as the `@latest` tag on npm now.

**Comment by supermacro** [comment]
https://github.com/supermacro/neverthrow/releases/tag/v2.5.0

**Comment by bastianh** [comment]
Yes.. I had no problem with the 2.2 version .. it startet when I started updating all the dependencies. It stopped working at all but after also updating rollup it worked again.
I'm now using 2.4.0 and rollup works, but issues the warning on every build.
Thanks for looking into it.. I will update to 2.5.0 asap.
