### ISSUE TITLE
add an alias for err

### ISSUE THREAD

**Issue by naseemkullah** [supermacro/neverthrow#82]
We are looking into using this lib across our org and we also use [pino](https://github.com/pinojs/pino) for logging across the many services and `err` is treated specially due to the [default serializers](https://github.com/pinojs/pino/blob/master/docs/api.md#serializers-object), in particular due to the default for objects named err to be serialized via [pino's error serializer](https://github.com/pinojs/pino-std-serializers#exportserrerror).

While we could import {err as someOtherVar} in every service using `neverthrow` to avoid conflicting with our error logging standard, it would be nice to have an alias name for `err`  in `neverthrow` that works in our setup.

Would you consider `error`(perhaps invites the same problem though for other contexts) or `notOk` (my personal favourite) or `erroredResult` as an additional alias export to `err` ?

**Comment by supermacro** [comment]
Hey @naseemkullah,

You mean TransitApp when you say "our org"? I'm a long time TransitApp user!

I understand that there's an unfortunate naming collision. However, I don't think creating an alias within `neverthrow` is the right approach.

Have you considered perhaps creating a module in your project that renames `err` to whatever the team would like (such as `error` or `notOk`?

```typescript
// inside of utils/result.ts or something similar

import nt from 'neverthrow'

export type Result<T, E> = nt.Result<T, E>
export type Ok<T, E> = nt.Ok<T, E>
export type NotOk<T, E> = nt.Err<T, E>

export const notOk = nt.err
export const ok = nt.ok
```

Then your team would only reference `utils/result`, and not `neverthrow`. Would that work?

**Comment by naseemkullah** [comment]
Thanks @supermacro yep Transit :)

That's a nice idea but I was hoping to avoid adding anything extra in our projects. `notOk` is pretty great imho, so if you ever reconsider adding the alias in the lib itself that would be swell, if not we will either use your suggestion in all our projects or simply `import {err as notOk}` each time.

**Comment by naseemkullah** [comment]
https://github.com/supermacro/neverthrow/pull/84 if you ever change your mind ;)

**Comment by supermacro** [comment]
I am going to be closing this issue. On a closing note, I thought of another idea. Within your build stage you could use `awk` + `sed` and friends to inject any code into `node_modules/neverthrow` ... just a thought .. and it wouldn't be many lines of code!
