### ISSUE TITLE
Returning a Result<void, Error>

### ISSUE THREAD

**Issue by JbIPS** [supermacro/neverthrow#97]
Hi,

I saw in the doc than you could return a `Result<void, Error>` but I struggle to find how to create it with `ok()`, since I have to give it an argument.

Is there a workaround or did I miss something?

Thank you

**Comment by JbIPS** [comment]
Seems like `ok(undefined)` do the trick but it's not very elegant. Is there another way?

**Comment by paduc** [comment]
Hello @JbIPS, I don't think it's possible to use `Result<void, Error>` indeed. I personally use `Result<null, Error>` along with `ok(null)`. I believe it's more elegant than `undefined`.

You're right that the docs should be amended to remove `Result<void, Error>`.

**Comment by JbIPS** [comment]
IMO `null` and `undefined`/`void` don't have the same semantic meaning and that's why they are clearly distinct in TypeScript.

A naive approach would be to set the `ok()` parameter to optional, but maybe there are complications I don't see.

**Comment by paduc** [comment]
In typescript `void` is a type which can have no value. Unfortunately, Typescript doesn't accept missing arguments when the type is `void` (yet?). See discussion [here](https://github.com/microsoft/TypeScript/issues/29131).

The reason I prefer `null` to `undefined` in this case, is because `null` "[represents the intentional absence of any object value](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null)".

**Comment by paduc** [comment]
> A naive approach would be to set the `ok()` parameter to optional, but maybe there are complications I don't see.

The complication to this is that the value is now `T | undefined` downstream. Meaning that when you unwrap your value at the end, you'll get a `T | undefined` which is unfortunate.
Also, you lose the warning if you return a `ok()` instead of `ok(myValue)` in your functions.

**Comment by supermacro** [comment]
The convention that I use and advocate is to only use `void` as return values for functions:

```typescript
const doesNotReturnAnything = (): void => {}
```

If that convention is adhered, then one would not use `void` elsewhere, including within `Result`s. 

As mentioned already, I would recommend using `null` or `undefined` instead.

**Comment by supermacro** [comment]
Going to be closing this issue soon unless there's a good reason to keep it open.

**Comment by JbIPS** [comment]
Thank you both for your help!
